// Teks halaman, EN + ID. Sedikit kata: visual yang bercerita. Batas kejujuran: tidak ada klaim keuntungan (docs/design/landing.md).

export type Lang = "en" | "id";

export const copy = {
  en: {
    nav: { journey: "How it works", proof: "Proof feed", book: "Bots", access: "Access", verify: "Verify", cta: "Open proof feed" },
    hero: {
      l1: "SIGNALS",
      l2: "SEALED",
      l3: "BEFORE THE OUTCOME",
      sub: "Fabius runs locked trading bots and commits every signal on BNB Chain before the market answers. Anyone can check it. No profit claims: paper only, for now.",
      primary: "See the proof feed",
      secondary: "Connect an agent",
      badge: "VERIFY YOURSELF · NO KEY · NO GAS · ",
      legend: { sealed: "rules locked on-chain", verified: "signals verified", empty: "empty: the record started" },
      live: "Live from chain 97",
    },
    journey: {
      tag: "01 — One signal",
      title: "From candle close to proof",
      stations: [
        { t: "00:00 UTC", h: "The bar closes", d: "Daily candle settles. Nothing after this moment can enter the signal." },
        { t: "+ seconds", h: "The bot decides", d: "One locked method, one parameter. Output: enter, exit or resize." },
        { t: "+ minutes", h: "Sealed", d: "Every signal is salted and folded into one Merkle root." },
        { t: "≤ 12 h", h: "Committed on BNB Chain", d: "The root lands in SignalAnchor. The block time is the alibi." },
        { t: "after", h: "Opened & checked", d: "Payloads are revealed. Anyone recomputes them from public bars." },
      ],
      verify: "python -X utf8 tools/verify_signals.py",
    },
    proof: {
      tag: "02 — Proof feed",
      title: "The track record, day by day",
      sub: "Each cell is one bot on one day. Holes stay holes: unmeasured is not zero.",
      states: { future: "not yet", prelock: "before lock", pending: "ticked, commit pending", sealed: "sealed", verified: "verified", gap: "gap", missed: "missed" },
      fd16: "Forward test before anything is sold (F-D16)",
      signals: "signals",
      days: "settled days",
      months: "months",
      settleNote: "Final settles wait for Binance's monthly funding file, so early days show none.",
      started: "Clock started",
    },
    book: {
      tag: "03 — The book",
      title: "Ten slots. One identity bot. Rules first.",
      sub: "A bot earns a slot through gates, then 60 days of shadow. Its spec hash is locked before its first trade.",
      identity: "identity",
      shadow: "shadow",
      locked: "spec hashed · no forward clock",
      locks: "Locked on-chain, in this order",
      lockNames: {
        "THRESHOLDS-v1": "Gate thresholds",
        "SPEC B1-TREND": "B1 spec",
        "SPEC B3-CARRY": "B3 spec",
        "FABIUS-FD16-MAJU-v1": "Forward-test rules",
        "FABIUS-BUKU-E690": "Slot book · epoch 690",
        "FABIUS-PEMBUNUH-v1": "Kill rules",
        "FABIUS-ANGGARAN-v1": "Gate error budget",
      } as Record<string, string>,
    },
    doors: {
      tag: "04 — Access",
      title: "Two doors. Same proof.",
      human: {
        k: "For people",
        h: "Proof feed",
        open: "Open · free",
        pts: ["Every commit as it lands", "Opened signals, checked against the chain", "The paper record, holes included"],
        cta: "Watch the proof feed",
        cta2: "Get notified on Telegram",
      },
      agent: {
        k: "For agents",
        h: "MCP + x402",
        open: "MCP server · live · tier 0",
        pts: ["Read the proof feed as tools", "Verify any signal against its root", "Pay per signal with x402 when tier 1 opens"],
        cta: "agent-card.json",
      },
      tier1: {
        k: "Tier 1",
        h: "Real-time signals",
        status: "Locked",
        why: "Opens only for a bot that passes the forward test, after a legal review.",
        rings: ["Forward test", "Legal review", "Go"],
        waitlist: "Join the waitlist",
      },
    },
    claims: "PAPER ONLY · NO EDGE CLAIMED · FORWARD TEST NOT YET MET · VERIFY, DON'T TRUST · EVERY RULE LOCKED BEFORE THE DATA · ",
    verify: {
      tag: "Verify — no key, no gas",
      t1: "Don't trust.",
      t2: "Check it.",
      sub: "Pick a bot and a day. This page reads the public ledger and BNB Chain at this moment, rebuilds every signal from its on-chain payload, and tells you whether it matches what was sealed before the market answered.",
      bot: "Bot",
      bar: "Bar (UTC day)",
      latest: "latest",
      go: "Verify",
      checking: "Reading BNB Chain…",
      stations: [
        { k: "01", h: "Ledger tick", d: "What the bot decided, written by the GitHub chain" },
        { k: "02", h: "Committed on-chain", d: "Merkle root in SignalAnchor; the block time is the alibi" },
        { k: "03", h: "Opened", d: "Each signal's payload revealed on-chain" },
        { k: "04", h: "Recomputed", d: "Leaf and id rebuilt from the payload, matched to the ledger" },
      ],
      verdicts: {
        SAH: "Verified",
        SEALED_NOT_YET_REVEALED: "Sealed, not yet opened",
        ALARM: "Alarm",
        NO_TICK: "No tick",
        BEFORE_LOCK: "Before the lock",
        BAR_NOT_CLOSED: "Bar not closed",
        AWAITING_COMMIT: "Waiting for the commit",
        NOT_COMMITTED: "Not committed",
      } as Record<string, string>,
      explain: {
        SAH: "Every signal of this day was committed before the outcome and recomputes exactly from what was revealed. Proof of timing, not of profit.",
        SEALED_NOT_YET_REVEALED: "The commit is on-chain; some payloads are still sealed. They must be opened within the reveal window.",
        ALARM: "Something does not match. The problems are listed below, exactly as found.",
        NO_TICK: "The public ledger has no tick for this bot on this day.",
        BEFORE_LOCK: "This day is older than the bot's on-chain spec lock, so it could not be committed. Recorded, not hidden.",
        BAR_NOT_CLOSED: "This day has not closed yet.",
        AWAITING_COMMIT: "The tick exists; the commit is still inside its allowed window.",
        NOT_COMMITTED: "The commit window passed without a commit. That is a visible miss.",
      } as Record<string, string>,
      signals: "signals",
      silent: "No signal today: the bot stayed put. The empty root is committed anyway.",
      emitted: "written",
      committed: "committed",
      afterClose: "h after close",
      root: "root",
      leafOk: "leaf recomputes",
      inLedger: "id in ledger",
      tx: "tx",
      problems: "Problems found",
      self: "Check it yourself",
      selfNote: "Same check, without this website:",
      raw: "Raw result (JSON)",
      share: "Link to this check",
      checkedAt: "checked",
      error: "Could not read the chain or the ledger right now. That is not a verdict; try again.",
      fromCalendar: "Verify a day",
    },
    bot: {
      tag: "Bot — one locked machine",
      rule: "The rule, as locked",
      gloss: "In English (the locked text is the Indonesian above)",
      param: "parameter",
      tier: "tier",
      assets: "assets",
      specLocked: "spec locked on-chain",
      specHashed: "spec hashed, not locked on-chain",
      clock: "forward clock since",
      role: { identity: "In the book · identity bot · slot", challenger: "Challenger · shadow", idle: "Spec hashed · not running" },
      idle: "This bot has a hashed spec but no forward clock: no ticks, no signals, no record. Shown so nothing is hidden; offered to no one.",
      about: "About this bot",
      book: {
        tag: "Paper book today",
        title: "What it holds right now",
        sub: "The last tick in the public ledger, read live. Paper: a position intent, not an order.",
        held: "held",
        flat: "flat",
        short: "short",
        entered: "new",
        exited: "exited",
        asof: "bar",
        written: "written",
        gross: "gross weight",
        error: "Could not read the public ledger right now. That does not mean flat.",
        none: "No tick yet.",
        verify: "Verify this day",
      },
      days: {
        tag: "Day by day",
        title: "Every closed day leaves a cube",
        sub: "One cube per day since the clock started. Holes stay holes. Click a day to check it against the chain.",
        afterClose: "h after close",
        noTick: "closed, tick pending",
        next: "next",
      },
      locks: {
        tag: "Locked, in time order",
        title: "The rules that bind it",
        sub: "Each lock is a transaction; its block time proves the rule existed before every day judged after it. Days before the spec lock are marked, not hidden.",
        firstTick: "First forward tick written",
      },
      fd16: { tag: "Forward test", title: "Nothing is sold before these fill", sub: "Locked thresholds (F-D16), counted from the public ledger. Settled days wait for Binance's monthly funding file." },
      kill: {
        tag: "When it dies",
        title: "The kill rule, fixed before the first signal",
        sub: "Part of the spec hash: changing a word means a new bot with a new ledger.",
        clauses: "How the machine checks it",
        locked: "Clauses locked on-chain before any final settle",
        textOnly: "No machine-checked clauses for this bot yet: the text is judged by a person.",
      },
    },
    foot: { contracts: "Contracts · BNB Chain testnet (97)", check: "Check it yourself", snapshot: "Snapshot", repo: "Source & ledger" },
  },
  id: {
    nav: { journey: "Cara kerja", proof: "Umpan bukti", book: "Bot", access: "Akses", verify: "Periksa", cta: "Buka umpan bukti" },
    hero: {
      l1: "SINYAL",
      l2: "DISEGEL",
      l3: "SEBELUM HASILNYA ADA",
      sub: "Fabius menjalankan bot trading terkunci dan mengomit setiap sinyal ke BNB Chain sebelum pasar menjawab. Siapa pun bisa memeriksa. Tanpa klaim untung: paper dulu.",
      primary: "Lihat umpan bukti",
      secondary: "Hubungkan agen",
      badge: "PERIKSA SENDIRI · TANPA KUNCI · TANPA GAS · ",
      legend: { sealed: "aturan terkunci di chain", verified: "sinyal terbukti", empty: "kosong: rekam jejak baru mulai" },
      live: "Langsung dari chain 97",
    },
    journey: {
      tag: "01 — Satu sinyal",
      title: "Dari tutup lilin sampai terbukti",
      stations: [
        { t: "00:00 UTC", h: "Bar tutup", d: "Lilin harian selesai. Tidak ada yang sesudah detik ini boleh masuk ke sinyal." },
        { t: "+ detik", h: "Bot memutuskan", d: "Satu metode terkunci, satu parameter. Hasil: masuk, keluar, atau ubah ukuran." },
        { t: "+ menit", h: "Disegel", d: "Tiap sinyal diberi garam lalu dilipat jadi satu akar Merkle." },
        { t: "≤ 12 jam", h: "Dikomit ke BNB Chain", d: "Akarnya masuk SignalAnchor. Jam blok adalah alibinya." },
        { t: "sesudah", h: "Dibuka & diperiksa", d: "Isinya dibuka. Siapa pun menghitung ulang dari bar publik." },
      ],
      verify: "python -X utf8 tools/verify_signals.py",
    },
    proof: {
      tag: "02 — Umpan bukti",
      title: "Rekam jejak, hari demi hari",
      sub: "Satu sel = satu bot pada satu hari. Hari bolong tetap bolong: tak terukur bukan nol.",
      states: { future: "belum", prelock: "sebelum kunci", pending: "tick ada, komit menunggu", sealed: "tersegel", verified: "terbukti", gap: "bolong", missed: "terlewat" },
      fd16: "Uji maju sebelum apa pun dijual (F-D16)",
      signals: "sinyal",
      days: "hari settle",
      months: "bulan",
      settleNote: "Settle final menunggu berkas funding bulanan Binance, jadi hari-hari awal belum punya.",
      started: "Jam mulai",
    },
    book: {
      tag: "03 — Buku slot",
      title: "Sepuluh slot. Satu bot identitas. Aturan dulu.",
      sub: "Bot masuk lewat gerbang, lalu 60 hari bayangan. Hash spesifikasinya dikunci sebelum transaksi pertamanya.",
      identity: "identitas",
      shadow: "bayangan",
      locked: "spesifikasi di-hash · belum ada jam maju",
      locks: "Terkunci di chain, dengan urutan ini",
      lockNames: {
        "THRESHOLDS-v1": "Ambang gerbang",
        "SPEC B1-TREND": "Spesifikasi B1",
        "SPEC B3-CARRY": "Spesifikasi B3",
        "FABIUS-FD16-MAJU-v1": "Aturan uji maju",
        "FABIUS-BUKU-E690": "Buku slot · epoch 690",
        "FABIUS-PEMBUNUH-v1": "Aturan buang bot",
        "FABIUS-ANGGARAN-v1": "Anggaran salah gerbang",
      } as Record<string, string>,
    },
    doors: {
      tag: "04 — Akses",
      title: "Dua pintu. Bukti yang sama.",
      human: {
        k: "Untuk manusia",
        h: "Umpan bukti",
        open: "Terbuka · gratis",
        pts: ["Setiap komit begitu masuk", "Sinyal yang dibuka, dicocokkan dengan chain", "Rekam jejak paper, hari bolong ikut tampil"],
        cta: "Lihat umpan bukti",
        cta2: "Kabari saya di Telegram",
      },
      agent: {
        k: "Untuk agen",
        h: "MCP + x402",
        open: "Server MCP · hidup · tingkat 0",
        pts: ["Baca umpan bukti sebagai tool", "Periksa sinyal mana pun terhadap akarnya", "Bayar per sinyal dengan x402 saat tingkat 1 dibuka"],
        cta: "agent-card.json",
      },
      tier1: {
        k: "Tingkat 1",
        h: "Sinyal waktu-nyata",
        status: "Terkunci",
        why: "Hanya dibuka untuk bot yang lolos uji maju, sesudah telaah hukum.",
        rings: ["Uji maju", "Telaah hukum", "Mulai"],
        waitlist: "Masuk daftar tunggu",
      },
    },
    claims: "PAPER SAJA · TANPA KLAIM EDGE · UJI MAJU BELUM TERPENUHI · PERIKSA, JANGAN PERCAYA · SEMUA ATURAN DIKUNCI SEBELUM DATA · ",
    verify: {
      tag: "Periksa — tanpa kunci, tanpa gas",
      t1: "Jangan percaya.",
      t2: "Periksa.",
      sub: "Pilih bot dan hari. Halaman ini membaca ledger publik dan BNB Chain saat ini juga, menyusun ulang setiap sinyal dari isinya di chain, lalu memberi tahu apakah cocok dengan yang disegel sebelum pasar menjawab.",
      bot: "Bot",
      bar: "Bar (hari UTC)",
      latest: "terbaru",
      go: "Periksa",
      checking: "Membaca BNB Chain…",
      stations: [
        { k: "01", h: "Tick ledger", d: "Keputusan bot, ditulis rantai GitHub" },
        { k: "02", h: "Dikomit di chain", d: "Akar Merkle di SignalAnchor; jam blok adalah alibinya" },
        { k: "03", h: "Dibuka", d: "Isi tiap sinyal diungkap di chain" },
        { k: "04", h: "Dihitung ulang", d: "Leaf dan id disusun ulang dari isinya, dicocokkan dengan ledger" },
      ],
      verdicts: {
        SAH: "SAH",
        SEALED_NOT_YET_REVEALED: "Tersegel, belum dibuka",
        ALARM: "Alarm",
        NO_TICK: "Tidak ada tick",
        BEFORE_LOCK: "Sebelum kunci",
        BAR_NOT_CLOSED: "Bar belum tutup",
        AWAITING_COMMIT: "Menunggu komit",
        NOT_COMMITTED: "Tidak dikomit",
      } as Record<string, string>,
      explain: {
        SAH: "Setiap sinyal hari ini dikomit sebelum hasilnya ada dan tersusun ulang persis dari yang dibuka. Bukti waktu, bukan bukti untung.",
        SEALED_NOT_YET_REVEALED: "Komit sudah ada di chain; sebagian isi masih tersegel dan wajib dibuka dalam jendela ungkap.",
        ALARM: "Ada yang tidak cocok. Masalahnya ditulis di bawah apa adanya.",
        NO_TICK: "Ledger publik tidak punya tick untuk bot ini di hari ini.",
        BEFORE_LOCK: "Hari ini lebih tua dari kunci spesifikasi bot di chain, jadi tidak bisa dikomit. Dicatat, tidak disembunyikan.",
        BAR_NOT_CLOSED: "Hari ini belum tutup.",
        AWAITING_COMMIT: "Tick sudah ada; komitnya masih di dalam jendela yang diizinkan.",
        NOT_COMMITTED: "Jendela komit lewat tanpa komit. Itu kelalaian yang terlihat.",
      } as Record<string, string>,
      signals: "sinyal",
      silent: "Tidak ada sinyal hari ini: bot diam. Akar kosong tetap dikomit.",
      emitted: "ditulis",
      committed: "dikomit",
      afterClose: "j sesudah tutup",
      root: "akar",
      leafOk: "leaf cocok",
      inLedger: "id di ledger",
      tx: "tx",
      problems: "Masalah yang ditemukan",
      self: "Periksa sendiri",
      selfNote: "Pemeriksaan yang sama, tanpa situs ini:",
      raw: "Hasil mentah (JSON)",
      share: "Tautan ke pemeriksaan ini",
      checkedAt: "diperiksa",
      error: "Chain atau ledger tidak terbaca saat ini. Itu bukan vonis; coba lagi.",
      fromCalendar: "Periksa satu hari",
    },
    bot: {
      tag: "Bot — satu mesin terkunci",
      rule: "Aturannya, persis seperti dikunci",
      gloss: "",
      param: "parameter",
      tier: "tier",
      assets: "aset",
      specLocked: "spesifikasi dikunci di chain",
      specHashed: "spesifikasi di-hash, belum dikunci di chain",
      clock: "jam maju sejak",
      role: { identity: "Di buku · bot identitas · slot", challenger: "Penantang · bayangan", idle: "Spesifikasi di-hash · tidak berjalan" },
      idle: "Bot ini punya spesifikasi yang di-hash tapi tanpa jam maju: tanpa tick, tanpa sinyal, tanpa rekam jejak. Ditampilkan agar tidak ada yang disembunyikan; tidak ditawarkan ke siapa pun.",
      about: "Tentang bot ini",
      book: {
        tag: "Buku paper hari ini",
        title: "Yang dipegang saat ini",
        sub: "Tick terakhir di ledger publik, dibaca langsung. Paper: niat posisi, bukan order.",
        held: "dipegang",
        flat: "flat",
        short: "short",
        entered: "baru",
        exited: "keluar",
        asof: "bar",
        written: "ditulis",
        gross: "bobot kotor",
        error: "Ledger publik tidak terbaca saat ini. Itu bukan berarti flat.",
        none: "Belum ada tick.",
        verify: "Periksa hari ini",
      },
      days: {
        tag: "Hari demi hari",
        title: "Tiap hari yang tutup meninggalkan satu kubus",
        sub: "Satu kubus per hari sejak jam mulai. Hari bolong tetap bolong. Klik satu hari untuk memeriksanya terhadap chain.",
        afterClose: "j sesudah tutup",
        noTick: "tutup, tick menunggu",
        next: "berikut",
      },
      locks: {
        tag: "Terkunci, urut waktu",
        title: "Aturan yang mengikatnya",
        sub: "Tiap kunci adalah transaksi; jam bloknya membuktikan aturan sudah ada sebelum setiap hari yang dinilai sesudahnya. Hari sebelum kunci spesifikasi ditandai, tidak disembunyikan.",
        firstTick: "Tick maju pertama ditulis",
      },
      fd16: { tag: "Uji maju", title: "Tidak ada yang dijual sebelum ini penuh", sub: "Ambang terkunci (F-D16), dihitung dari ledger publik. Hari settle menunggu berkas funding bulanan Binance." },
      kill: {
        tag: "Kapan ia dimatikan",
        title: "Aturan buang, ditetapkan sebelum sinyal pertama",
        sub: "Bagian dari hash spesifikasi: mengubah satu kata berarti bot baru dengan ledger baru.",
        clauses: "Cara mesin memeriksanya",
        locked: "Syarat dikunci di chain sebelum ada settle final",
        textOnly: "Belum ada syarat yang diperiksa mesin untuk bot ini: teksnya dinilai manusia.",
      },
    },
    foot: { contracts: "Kontrak · BNB Chain testnet (97)", check: "Periksa sendiri", snapshot: "Snapshot", repo: "Kode & ledger" },
  },
} as const;

export type Copy = (typeof copy)["en"];

/** Glos EN untuk teks spesifikasi yang DIKUNCI dalam bahasa Indonesia (engine/spec.py, engine/locks/pembunuh.lock.json). Terjemahan, bukan teks yang dikunci. */
export const GLOSS: { methods: Record<string, string>; killers: Record<string, string>; clauses: Record<string, string> } = {
  methods: {
    "B1-TREND": "Long when the close is above the close N days ago, otherwise flat (time-series momentum, long/flat).",
    "B2-RS": "Long the top k and short the bottom k by L-day return (relative-strength rotation, dollar-neutral); 7 sub-books, each rebalanced weekly on a different UTC weekday (no day picking).",
    "B3-CARRY": "Long spot + short perp while the 7-day average funding (annualised) is above theta, otherwise flat.",
    "B4-LISTING-FADE": "Short a newly listed perp at its day-1 close; close after H days; small size, isolated margin.",
    "B5-CORE-RWA": "BTC and gold weighted by 1/sigma (sigma = standard deviation of L days of daily returns); weights refreshed monthly.",
    "B6-BOUNCE": "Buy when the price z-score (N-day mean and standard deviation) is below −z_entry; exit at z ≥ 0 (long/flat).",
  },
  killers: {
    "B1-TREND": "12 forward months without beating buy & hold on both MDD and Sharpe; or losing to a random-entry placebo with the same holding-time distribution.",
    "B2-RS": "Net Sharpe below 0 for two quarters in a row, or not beating a random-rank placebo.",
    "B3-CARRY": "Hedged result negative for three running months while active, or one ADL event on the perp leg.",
    "B4-LISTING-FADE": "20 forward listings with mean short PnL ≤ 0, or one trade worse than −100% of notional.",
    "B5-CORE-RWA": "Sharpe below BTC buy & hold AND max drawdown no better than −50% over 12 forward months.",
    "B6-BOUNCE": "Forward signals do not raise the equal-weight Sharpe, or n ≥ 20 signals with mean net ≤ 0.",
  },
  clauses: {
    "B1-K1": "Fires unless (bot Sharpe > benchmark Sharpe AND bot MDD > benchmark MDD) over 365 forward days with ≥ 90 % settled coverage; benchmark = equal-weight buy & hold of the same 16 perps, no costs.",
    "B1-K2": "Fires if bot net ≤ the median net of 1,000 circular-shift placebos (same exposure, same holding time).",
    "B3-K1": "Fires if each of the last three finished, active calendar months (≥ 10 days holding) is net < 0; dormant months are skipped, not counted as zero.",
    "B3-K2": "Fires on the first ADL event on the perp leg; not applicable on paper.",
  },
};

export const LINKS = {
  repo: "https://github.com/Shenhan01-sys/Fabius",
  ledger: "https://github.com/Shenhan01-sys/Fabius/tree/master/ledger/paper",
  agentCard: "https://raw.githubusercontent.com/Shenhan01-sys/Fabius/master/docs/agent-card.json",
  telegram: "https://t.me/FabiusTradingAgent_Bot",
  scan: "https://testnet.bscscan.com/address/",
  tx: "https://testnet.bscscan.com/tx/",
};
