// Teks halaman, EN + ID. Sedikit kata: visual yang bercerita. Batas kejujuran: tidak ada klaim keuntungan (docs/design/landing.md).

export type Lang = "en" | "id";

export const copy = {
  en: {
    nav: { journey: "How it works", proof: "Proof feed", book: "Bots", access: "Access", verify: "Verify", status: "Status", analysts: "Analysts", desk: "AI Desk", cta: "Open proof feed", signIn: "Sign in", signedIn: "Signed in", member: "Member", submit: "Submit bot", submitMenu: "Submit", submitAgent: "Submit agent" },
    login: {
      welcome: "Welcome to Fabius",
      welcomeSub: "Sign in to watch the AI desk live and read every analyst's reasoning before the bar closes.",
      google: "Continue with Google",
      telegram: "Continue with Telegram",
      orEmail: "or use your email",
      emailPlaceholder: "you@example.com",
      continue: "Continue",
      sending: "Sending code…",
      codeSent: "We sent a 6-digit code to {e}",
      codeLabel: "Login code",
      verify: "Verify and sign in",
      verifying: "Signing in…",
      otherEmail: "Use another email",
      resend: "Resend code",
      redirecting: "Opening {p}…",
      newHere: "New here? Signing in creates your wallet on BNB testnet automatically. Paper trading only, nothing to pay.",
      close: "Close",
      account: "Your account",
      via: "Signed in with {m}",
      wallet: "Wallet",
      copy: "Copy",
      copied: "Copied",
      checking: "Checking membership…",
      member: "Member until {d}",
      lastBuy: "last signal bought: {bot} · bar {bar}",
      notMember: "Not a member yet",
      notMemberSub: "Buy 1 signal and the AI desk and the analysts' reasoning go live for 7 days. The buy page tops up free test FAB, no tBNB needed.",
      buy: "Buy 1 signal",
      openDesk: "AI desk",
      openAnalysts: "Analysts",
      signOut: "Sign out",
      error: "Something went wrong",
      line: {
        member: "Member · live until {d}",
        signedNoBuy: "Signed in, not a member yet.",
        publicDesk: "Public view: decisions appear 24 h after each cycle; equity, results and on-chain proofs are live.",
        publicAnalysts: "Public view: reasoning for an open bar is sealed until the bar closes; members read it now.",
        signIn: "Sign in",
        buy: "Buy 1 signal",
      },
    },
    hero: {
      l1: "SIGNALS",
      l2: "SEALED",
      l3: "BEFORE THE OUTCOME",
      sub: "Fabius runs locked trading bots and commits every signal on BNB Chain before the market answers. Anyone can check it. No profit claims: paper only, for now.",
      primary: "See the proof feed",
      secondary: "Connect an agent",
      badge: "VERIFY YOURSELF · NO KEY · NO GAS · ",
      legend: { sealed: "rules locked on-chain", verified: "signals verified", empty: "empty: the record started" },
      live: "Live from chain 97",
    },
    journey: {
      tag: "01 — One signal",
      title: "From candle close to proof",
      stations: [
        { t: "00:00 UTC", h: "The bar closes", d: "Daily candle settles. Nothing after this moment can enter the signal." },
        { t: "+ seconds", h: "The bot decides", d: "One locked method, one parameter. Output: enter, exit or resize." },
        { t: "+ minutes", h: "Sealed", d: "Every signal is salted and folded into one Merkle root." },
        { t: "≤ 12 h", h: "Committed on BNB Chain", d: "The root lands in SignalAnchor. The block time is the alibi." },
        { t: "after", h: "Opened & checked", d: "Payloads are revealed. Anyone recomputes them from public bars." },
      ],
      verify: "python -X utf8 tools/verify_signals.py",
    },
    proof: {
      tag: "02 — Proof feed",
      title: "The track record, day by day",
      sub: "Each cell is one bot on one day. Holes stay holes: unmeasured is not zero.",
      states: { future: "not yet", prelock: "before lock", pending: "ticked, commit pending", sealed: "sealed", verified: "verified", gap: "gap", missed: "missed" },
      fd16: "Forward test before anything is sold (F-D16)",
      signals: "signals",
      days: "settled days",
      months: "months",
      settleNote: "Final settles wait for Binance's monthly funding file, so early days show none.",
      started: "Clock started",
    },
    book: {
      tag: "03 — The book",
      title: "Ten slots. One identity bot. Rules first.",
      sub: "A bot earns a slot through gates, then 60 days of shadow. Its spec hash is locked before its first trade.",
      identity: "identity",
      shadow: "shadow",
      locked: "spec hashed · no forward clock",
      locks: "Locked on-chain, in this order",
      lockNames: {
        "THRESHOLDS-v1": "Gate thresholds",
        "SPEC B1-TREND": "B1 spec",
        "SPEC B3-CARRY": "B3 spec",
        "SPEC B2-RS": "B2 spec",
        "SPEC B4-LISTING-FADE": "B4 spec",
        "SPEC B5-CORE-RWA": "B5 spec",
        "SPEC B6-BOUNCE": "B6 spec",
        "FABIUS-FD16-MAJU-v1": "Forward-test rules",
        "FABIUS-BUKU-E690": "Slot book · epoch 690",
        "FABIUS-PEMBUNUH-v1": "Kill rules",
        "FABIUS-ANGGARAN-v1": "Gate error budget",
      } as Record<string, string>,
    },
    doors: {
      tag: "04 — Access",
      title: "Two doors. Same proof.",
      human: {
        k: "For people",
        h: "Proof feed",
        open: "Open · free",
        pts: ["Every commit as it lands", "Opened signals, checked against the chain", "The paper record, holes included"],
        cta: "Watch the proof feed",
        cta2: "Get notified on Telegram",
      },
      agent: {
        k: "For agents",
        h: "MCP + x402",
        open: "MCP server · live · tier 0",
        pts: ["Read the proof feed as tools", "Verify any signal against its root", "Pay per signal with x402 when tier 1 opens"],
        cta: "agent-card.json",
      },
      tier1: {
        k: "Tier 1",
        h: "Real-time signals",
        status: "Locked",
        why: "Opens only for a bot that passes the forward test, after a legal review.",
        rings: ["Forward test", "Legal review", "Go"],
        waitlist: "Join the waitlist",
      },
    },
    label: {
      INTI: "Core",
      SEMENTARA: "Provisional",
      note: {
        INTI: "Holds the book's identity slot (builder's choice). Not proof of being the best: no bot has passed the forward test yet.",
        SEMENTARA: "Runs in public, and can be replaced by any bot that meets the criteria.",
      } as Record<string, string>,
      gate: "gate v1",
      verdict: { LOLOS_SHADOW: "passed", TOLAK: "rejected", TIDAK_TERUKUR: "not measurable" } as Record<string, string>,
      fd16: { LOLOS: "passed", "BELUM CUKUP DATA": "not enough data yet", "TIDAK LOLOS": "failed" } as Record<string, string>,
      conf: { "belum terukur": "not measured yet", "awal - belum bermakna": "early, not meaningful yet", terukur: "measured" } as Record<string, string>,
    },
    claims: "PAPER ONLY · NO EDGE CLAIMED · FORWARD TEST NOT YET MET · VERIFY, DON'T TRUST · EVERY RULE LOCKED BEFORE THE DATA · ",
    verify: {
      tag: "Verify — no key, no gas",
      t1: "Don't trust.",
      t2: "Check it.",
      sub: "Pick a bot and a day. This page reads the public ledger and BNB Chain at this moment, rebuilds every signal from its on-chain payload, and tells you whether it matches what was sealed before the market answered.",
      bot: "Bot",
      bar: "Bar (UTC day)",
      latest: "latest",
      go: "Verify",
      checking: "Reading BNB Chain…",
      stations: [
        { k: "01", h: "Ledger tick", d: "What the bot decided, written by the GitHub chain" },
        { k: "02", h: "Committed on-chain", d: "Merkle root in SignalAnchor; the block time is the alibi" },
        { k: "03", h: "Opened", d: "Each signal's payload revealed on-chain" },
        { k: "04", h: "Recomputed", d: "Leaf and id rebuilt from the payload, matched to the ledger" },
      ],
      verdicts: {
        SAH: "Verified",
        SEALED_NOT_YET_REVEALED: "Sealed, not yet opened",
        ALARM: "Alarm",
        NO_TICK: "No tick",
        BEFORE_LOCK: "Before the lock",
        BAR_NOT_CLOSED: "Bar not closed",
        AWAITING_COMMIT: "Waiting for the commit",
        NOT_COMMITTED: "Not committed",
      } as Record<string, string>,
      explain: {
        SAH: "Every signal of this day was committed before the outcome and recomputes exactly from what was revealed. Proof of timing, not of profit.",
        SEALED_NOT_YET_REVEALED: "The commit is on-chain; some payloads are still sealed. They must be opened within the reveal window.",
        ALARM: "Something does not match. The problems are listed below, exactly as found.",
        NO_TICK: "The public ledger has no tick for this bot on this day.",
        BEFORE_LOCK: "This day is older than the bot's on-chain spec lock, so it could not be committed. Recorded, not hidden.",
        BAR_NOT_CLOSED: "This day has not closed yet.",
        AWAITING_COMMIT: "The tick exists; the commit is still inside its allowed window.",
        NOT_COMMITTED: "The commit window passed without a commit. That is a visible miss.",
      } as Record<string, string>,
      signals: "signals",
      silent: "No signal today: the bot stayed put. The empty root is committed anyway.",
      emitted: "written",
      committed: "committed",
      afterClose: "h after close",
      root: "root",
      leafOk: "leaf recomputes",
      inLedger: "id in ledger",
      tx: "tx",
      problems: "Problems found",
      self: "Check it yourself",
      selfNote: "Same check, without this website:",
      raw: "Raw result (JSON)",
      share: "Link to this check",
      checkedAt: "checked",
      error: "Could not read the chain or the ledger right now. That is not a verdict; try again.",
      fromCalendar: "Verify a day",
    },
    status: {
      tag: "Status — health, not performance",
      t1: "Is the machine",
      t2: "alive today?",
      sub: "One UTC day of operations, read live from the public ledger, BNB Chain and GitHub. No key. A failed read shows as unreadable, never as fine and never as an alarm.",
      overall: { ok: "All stations normal", wait: "Running: waiting on a station", alarm: "Alarm", unreadable: "Partly unreadable" } as Record<string, string>,
      checked: "read",
      refresh: "Read again",
      reading: "Reading the ledger, BNB Chain and GitHub…",
      error: "This page could not read its sources right now. That is not a verdict; try again.",
      dial: { title: "Today's bar", closed: "closed", ago: "h ago", window: "tick window", commitLag: "commit within", revealWin: "reveal within", now: "now", h: "h" },
      bots: { tag: "01 — Stations, per bot", title: "Where today's bar is", sub: "The same bar walks every station. A lamp lights when its step is done; a waiting lamp says what it waits for." },
      stations: {
        close: { h: "Bar closed", who: "00:00 UTC" },
        tick: { h: "Ledger tick", who: "GitHub chain" },
        commit: { h: "Committed", who: "Railway worker → SignalAnchor" },
        reveal: { h: "Opened", who: "Railway worker" },
        kertas: { h: "Venue-rules paper", who: "GitHub chain · Binance + Aster rules · 10 USDT" },
        exec: { h: "Demo execution", who: "Railway · Binance demo → Gist → GitHub ledger" },
      } as Record<string, { h: string; who: string }>,
      codes: {
        CLOSED: "closed",
        TICK_OK: "signals written: {d}",
        TICK_BEFORE_WINDOW: "window opens {at}",
        TICK_IN_WINDOW: "inside the window, polled every 5 min until 11:58 UTC",
        TICK_GAP: "gap recorded: unmeasured, not zero",
        TICK_MISSED: "no tick 12 h after close",
        NEEDS_TICK: "after the tick",
        NEEDS_COMMIT: "after the commit",
        UNREADABLE: "could not read: not a verdict",
        COMMIT_OK: "root committed · signals: {d}",
        COMMIT_GRACE: "grace until {at}",
        WORKER_SILENT: "worker silent for {d} min",
        REVEAL_OK: "{d} opened",
        REVEAL_SILENT: "silent day: nothing to open",
        REVEAL_PENDING: "{d} opened · grace until {at}",
        REVEAL_STUCK: "stuck at {d}",
        KERTAS_OK: "up to date",
        KERTAS_BEHIND: "behind: 1-minute prices for the commit time arrive a day later",
        KERTAS_NA: "not run for this bot",
        EXEC_PRIVATE: "runs with API keys on Railway; its public ledger starts when the report feed is switched on (F-D94)",
        EXEC_OK: "in the public ledger: {d} orders",
        EXEC_OK_REAL: "in the public ledger: {d} (real money)",
        EXEC_OK_SWITCH_OFF: "in the public ledger: {d} demo orders · real-money switch OFF (config/uang_nyata.json)",
        EXEC_OK_SWITCH_ON: "in the public ledger: {d} demo orders · real-money switch ON, no real-money report for this bar yet",
        EXEC_WAIT: "executor acts after the commit; report due by {at}",
        EXEC_MISSING: "no execution report {d} min after the commit",
        EXEC_VIOLATION: "safety violations recorded: {d}",
        EXEC_NA: "not executed for this bot",
      } as Record<string, string>,
      lamps: { ok: "done", wait: "waiting", alarm: "alarm", unreadable: "unreadable", later: "not yet", private: "not public", na: "not applicable" } as Record<string, string>,
      verifyBar: "Verify this bar",
      plant: { tag: "02 — The plant", title: "Fuel, clock and memory", sub: "What keeps the stations running: gas for the committer, the chain head, and when the landing data was last printed." },
      gas: { h: "Committer gas", alert: "operator alert", refill: "builder refills", unit: "tBNB" },
      chain: { h: "BNB Chain testnet", block: "block", commits: "commits on SignalAnchor" },
      snap: { h: "Landing snapshot", printed: "printed", block: "at block" },
      beat: {
        tag: "03 — Heartbeat",
        title: "The GitHub chain that writes the ledger",
        sub: "paper-ledger.yml dispatches itself: one run loops for hours, then starts the next. Its commits carry GitHub's clock, not ours.",
        success: "success",
        failure: "failed",
        running: "running",
        other: "other",
        open: "Open on GitHub",
      },
    },
    bot: {
      tag: "Bot — one locked machine",
      rule: "The rule, as locked",
      gloss: "In English (the locked text is the Indonesian above)",
      original: "Locked original text (Indonesian, hashed on-chain)",
      param: "parameter",
      tier: "tier",
      assets: "assets",
      specLocked: "spec locked on-chain",
      specHashed: "spec hashed, not locked on-chain",
      clock: "forward clock since",
      role: { identity: "In the book · identity bot · slot", challenger: "Challenger · shadow", idle: "Spec hashed · not running" },
      idle: "This bot has a hashed spec but no forward clock: no ticks, no signals, no record. Shown so nothing is hidden; offered to no one.",
      about: "About this bot",
      book: {
        tag: "Paper book today",
        title: "What it holds right now",
        sub: "The last tick in the public ledger, read live. Paper: a position intent, not an order.",
        held: "held",
        flat: "flat",
        short: "short",
        entered: "new",
        exited: "exited",
        asof: "bar",
        written: "written",
        gross: "gross weight",
        error: "Could not read the public ledger right now. That does not mean flat.",
        none: "No tick yet.",
        verify: "Verify this day",
      },
      days: {
        tag: "Day by day",
        title: "Every closed day leaves a cube",
        sub: "One cube per day since the clock started. Holes stay holes. Click a day to check it against the chain.",
        afterClose: "h after close",
        noTick: "closed, tick pending",
        next: "next",
      },
      locks: {
        tag: "Locked, in time order",
        title: "The rules that bind it",
        sub: "Each lock is a transaction; its block time proves the rule existed before every day judged after it. Days before the spec lock are marked, not hidden.",
        firstTick: "First forward tick written",
      },
      exec: {
        tag: "Executed in a demo account",
        title: "Paper, venue rules, then real fills",
        sub: "The same decision three times: the paper ledger fills at the bar close, the venue-rules paper fills two minutes after the commit, and a Binance demo account fills for real. Virtual balance: no profit numbers.",
        paper: "paper = close",
        kertas: "venue-rules paper",
        real: "real fill",
        none: "no orders: positions already matched the target",
        filled: "weight filled",
        backfill: "backfilled",
        badgeReal: "REAL",
        badgeDemo: "demo",
        realFills: "real-money fills",
        realNote: "Binance live account, one-asset canary <= 10 USDT",
        latency: "commit → last fill",
        fee: "real fee",
        vsKertas: "real vs venue-rules paper",
        violations: "safety violations",
        notional: "notional",
        target: "PRD target",
        info: "measured, no target yet",
        note: "Right of the close mark = worse for us (paid more on a buy, got less on a sell). Every order is checked against the on-chain commit time before it is written: an order sent before its commit would show here as a violation. Source: ledger/eksekusi, written by the GitHub chain from the executor's public Gist.",
        error: "Could not read the execution ledger right now. That does not mean nothing was executed.",
      },
      fd16: {
        tag: "Forward test",
        title: "Nothing is sold before these fill",
        sub: "Locked thresholds (F-D16), counted from the public ledger. Settled days wait for Binance's monthly funding file.",
        conf: "Confidence · forward record",
        confNone: "Not measured: fewer than 2 settled forward days, so no number at all.",
        confEarly: "Early: computed, but below the F-D16 thresholds, so not meaningful yet.",
        confOk: "Measured against the locked F-D16 thresholds.",
        confBasis: "1 − p of the locked F-D16 block bootstrap (null: mean net daily forward return ≤ 0). How sure the forward record is that this bot earns after costs — not the chance that today's signal is right. Never includes assets, direction or size.",
        day: "day",
      },
      kill: {
        tag: "When it dies",
        title: "The kill rule, fixed before the first signal",
        sub: "Part of the spec hash: changing a word means a new bot with a new ledger.",
        clauses: "How the machine checks it",
        locked: "Clauses locked on-chain before any final settle",
        textOnly: "No machine-checked clauses for this bot yet: the text is judged by a person.",
      },
    },
    beli: {
      tag: "Buy a signal · x402 · BNB testnet",
      title: "Buy {bot}'s latest signal",
      titleToday: "Buy today's Fabius signal",
      subToday: "One signal: the bot Fabius trades today, chosen by a locked rule from the AI analysts' picks. You don't pick a bot. Pay with x402: sign in with Google, Telegram or email, a wallet is created for you, no gas. FAB is a test token with no value.",
      today: "Fabius trades today",
      sub: "Pay per signal with x402. Sign in with Google, Telegram or email: a wallet is created for you and you pay no gas. FAB is a test token with no value. You pay for delivery and proof, not a secret: the bots are deterministic and open.",
      offer: "The offer",
      confidence: "confidence",
      notMeasured: "not measured yet",
      gate: "locked backtest gate",
      priceRule: "Price from a table locked before any forward data (F-D100): it rises only when the forward record is measured.",
      loading: "Loading…",
      wallet: "Your wallet",
      login: "Sign in (Google · Telegram · email)",
      creating: "creating your wallet…",
      noGas: "no tBNB needed",
      topup: "Get free FAB",
      logout: "sign out",
      payTitle: "Pay and reveal",
      pay: "Pay {fab} FAB and reveal",
      paying: "Signing and settling…",
      needTopup: "Not enough FAB yet: get free FAB above first.",
      result: "Your signal",
      flat: "Flat: no positions this bar.",
      committed: "committed on-chain",
      paidTx: "payment transaction on BscScan",
      disclaimer: "Paper position intents, not orders and not investment advice. Testnet only.",
      botTitle: "Telegram bot payments (optional)",
      botSub: "Let the Fabius bot pay for you so /buy works directly in Telegram. The Fabius server only asks it to sign the exact FAB price of a signal to the Fabius gate (enforced by a Privy policy inside Privy's enclave: FAB payments to the Fabius gate only, at most 1 FAB per signature, BNB testnet). Revoke any time. Testnet test tokens only.",
      botAllow: "Allow Fabius bot to pay for me",
      tgNeed: "Your Telegram is not linked to this wallet yet, so the bot cannot find it. Link it once:",
      tgLink: "Link my Telegram",
      tgWorking: "Linking…",
      tgDone: "Telegram linked. Go back to the chat and send /buy.",
      tgFail: "Telegram link failed",
      analystsOpen: "The AI analysts' full reasoning is now open for 7 days →",
      tgOk: "Telegram linked ({u}): /buy in the bot uses this wallet.",
      botRevoke: "revoke",
      botOn: "Allowed: /buy now pays directly in Telegram.",
      botOff: "Revoked: the bot can no longer pay from your wallet.",
      rule: "Rule (locked)",
      changes: "Changes vs previous bar",
      enter: "enter",
      exit: "exit",
      noTp: "No take-profit or stop-loss outside the rule: a position exits only when the rule flips, judged on the daily close (00:00 UTC), not intraday.",
      colAsset: "asset",
      colSide: "side",
      colWeight: "weight",
      colEntry: "entry (rule)",
      colExit: "exit next bar if close ≤",
      trailing: "Exit levels move every day with the window: they behave like a trailing stop on the daily close. Entry = close of the first bar of the current long run.",
    },
    submit: {
      tag: "Open bot program",
      title: "Submit a bot",
      sub: "Write your own rule: pick features, compare them, combine conditions, choose how to size positions, then sign the form with your wallet. Fabius' engine runs it through the same public gates that judge its own bots. If it passes it runs forward on paper for 60 days before it can take a slot. Every step is public and nothing here needs money.",
      board: "Pipeline",
      boardSub: "Every submission and where it is now. Reviews run once a day in the public repo.",
      stages: { received: "Received", reviewed: "Gates G1-G11 + KPI", shadow: "Forward shadow", slot: "Slot" },
      status: { "waiting for review": "waiting for review", queued: "queued (family cooldown)", reviewed: "reviewed", rejected: "rejected", shadow: "in forward shadow", "in slot": "in a slot" } as Record<string, string>,
      empty: "No submissions yet. Be the first.",
      days: "day {n} of {m}",
      form: "Your bot",
      signInFirst: "Sign in first: your wallet signs the submission.",
      signIn: "Sign in",
      wallet: "Issuer and payout wallet: {w} (your sign-in wallet)",
      universe: "Universe",
      add: "Add",
      remove: "Remove",
      sections: { spec: "Method", identity: "Who you are", theory: "Why it should work", evidence: "Your evidence", declarations: "Declarations" } as Record<string, string>,
      optional: "optional",
      check: "Check form",
      checking: "Checking…",
      sign: "Sign and submit",
      signing: "Waiting for your wallet…",
      sending: "Submitting…",
      problems: "The gate rejected the form:",
      sent: "Received. ID {id}. The next daily review will judge it; follow it in the pipeline above.",
      contactNote: "Your contact stays private at the gate: it is not hashed, not published and never goes on-chain.",
      rule: {
        kindTitle: "Kind",
        kinds: {
          rule: { name: "Rule", text: "You compose a rule from Fabius' vocabulary and our engine runs it. The rule is published with your form." },
          code: { name: "Code", text: "Your own function in a sandbox. Private." },
          feed: { name: "Feed", text: "Your program publishes its own signals, judged forward only." },
        },
        soon: "soon",
        publicNote: "A rule is published with your form (never your contact) so anyone can re-run the review. Kinds that keep the method private (code, feed) come later.",
        modeTitle: "How it decides",
        modes: {
          per_aset: { name: "Each asset on its own", text: "Every asset has its own state (flat, long or short) switched by your conditions." },
          peringkat: { name: "Rank the assets", text: "Every day score all assets, long the top and short the bottom (market-neutral)." },
        },
        paramsTitle: "Named parameters",
        paramsHelp: "Numbers you name and reuse. Fabius shifts each one (x0.5 to x1.5, alone and all together) to test whether the rule is robust: a rule with no named parameter cannot show that, and one whose parameters change nothing fails the plateau gate. Every variant counts as an attempt in the Sharpe bar.",
        addParam: "Add parameter",
        paramName: "name",
        paramValue: "value",
        used: "used",
        unused: "not used yet",
        dup: "duplicate name",
        undeclared: "Used but not declared: {n}",
        slots: { masuk_long: "Enter long when", keluar_long: "Exit long when", masuk_short: "Enter short when", keluar_short: "Exit short when" },
        slotAuto: "Empty: exit as soon as the entry condition is no longer true.",
        addSlot: "Add",
        removeSlot: "Remove",
        strip: { flat: "flat", long: "long", short: "short", enter: "enter", exit: "exit", auto: "exit (automatic)", off: "off" },
        scoreTitle: "Score each asset by",
        topK: "Long the top",
        bottomK: "Short the bottom",
        minAssets: "Needs at least",
        assetsRanked: "assets with a score",
        rotation: "Rebalance",
        rotations: { harian: "Every day", tujuh_sub_buku: "Seven sub-books, averaged (one per weekday)" },
        weightsTitle: "Position sizing",
        schemes: { sama: "Equal weight", inv_vol: "Inverse volatility" },
        gross: "Max total exposure",
        grossHelp: "up to {m}",
        volWindow: "Volatility window (days)",
        ours: "Fees, funding and the cost model are Fabius': you write only the rule.",
        expr: {
          kind: "kind",
          kinds: { f: "feature", c: "number", p: "parameter", op: "math", fn: "function" },
          n: "window (days)",
          lag: "days ago",
          addLag: "+ days ago",
          noParams: "declare a parameter first",
        },
        cond: { kind: "kind", kinds: { cmp: "compare", and: "all of", or: "any of", not: "not" }, add: "+ condition" },
        features: {
          close: "closing price",
          open: "opening price",
          high: "high",
          low: "low",
          volume: "volume",
          ret: "return over n days",
          sma: "simple moving average of closes",
          ema: "exponential moving average of closes",
          std: "standard deviation of closes",
          zscore: "z-score of the close vs its n-day mean",
          rsi: "relative strength index, 0-100",
          atr_pct: "average true range, % of price",
          max_high: "highest high of n days",
          min_low: "lowest low of n days",
          vol_ratio: "today's volume vs the previous n-day average",
          drawdown: "distance from the n-day high (0 or below)",
        },
        readout: "Your rule in plain words",
        counters: "{n} of {m} nodes · depth {d} of {x} · window work {w} of {b}",
        showJson: "Show the rule as JSON",
      },
      labels: {
        "spec.bot_id": "Bot ID", "spec.metode": "Method in one sentence", "identity.handle": "Public name",
        "identity.contact": "Contact (private)", "identity.entity_type": "You are", "identity.erc8004_agent_id": "ERC-8004 agent ID", "identity.conflicts": "Relevant interests or positions ('none' if none)",
        "theory.mekanisme_jenis": "Mechanism type", "theory.mekanisme": "Why this method makes money", "theory.pihak_seberang": "Who pays for this edge and why it is not arbitraged away",
        "theory.kapasitas_usd": "Estimated capacity (USD)", "theory.referensi": "References (at least one)", "theory.referensi.judul": "Title", "theory.referensi.url": "Public https URL",
        "theory.referensi.klaim": "What it shows", "theory.rezim": "When it works and when it fails", "theory.mode_gagal": "Failure modes and tail risk",
        "theory.peluruhan": "Still working in the last 24 months? Evidence?", "theory.pembunuh.metric": "Kill switch metric", "theory.pembunuh.comparator": "Comparator",
        "theory.pembunuh.threshold": "Threshold", "theory.pembunuh.window_sinyal": "Window (signals)", "evidence.sumber_data": "Data sources", "evidence.insample_mulai": "In-sample start",
        "evidence.insample_akhir": "In-sample end", "evidence.oos_mulai": "Out-of-sample start", "evidence.oos_akhir": "Out-of-sample end",
        "evidence.percobaan": "Variants tried before choosing this one (honest: it raises the Sharpe bar)", "evidence.klaim.sharpe_net": "Claimed net Sharpe",
        "evidence.klaim.mdd_pct": "Claimed max drawdown (%)", "evidence.klaim.n_sinyal": "Claimed number of signals", "evidence.klaim.tahunan_pct": "Claimed annual return (%)",
        "declarations.tanpa_lookahead": "No look-ahead", "declarations.tanpa_info_orang_dalam": "No insider information", "declarations.tanpa_wash_trading": "No wash trading or manipulation",
        "declarations.menerima_protokol": "I accept the selection, rolling and removal protocol", "declarations.izin_publikasi": "Results may be published, including bad ones",
        "declarations.lisensi": "Method licence",
      } as Record<string, string>,
    },
    submitAgent: {
      tag: "Open agent program",
      title: "Submit an agent",
      sub: "Bring your own AI agent to Fabius' 5-minute desk. It pulls the same input as the house agents and answers with a signed JSON. It starts in a trial seat (recorded and anchored on-chain, not counted in the consensus) and earns an active seat only by the locked seat rules. Fabius never holds your key and never calls your model.",
      board: "External agents",
      boardSub: "Every agent that registered, its seat and how healthy its answers are. Live from the gate.",
      empty: "No external agents yet. Be the first.",
      cols: { agent: "Agent", seat: "Seat", valid: "Valid answers", cycles: "Cycles seen", link: "Polling" },
      seats: { aktif: "active", uji: "trial", antre: "queue", keluar: "out" } as Record<string, string>,
      noSeat: "no seat yet",
      removed: "removed after repeated failures",
      online: "polling now",
      offline: "offline",
      howTitle: "How it works",
      steps: [
        { h: "Register once", p: "Sign a short message with the agent wallet or with the wallet that owns its ERC-8004 identity on BNB testnet (chain 97). Use the form below or the reference client." },
        { h: "Pull every cycle", p: "Every 5 minutes (UTC) fetch your input: the same prompt the house agents get (market data, your own paper book, the rules of the locked bots). Each pull is signed, so nobody else can fake your presence." },
        { h: "Answer, signed", p: "Reply before the deadline with the v2 answer JSON. The gate checks the format at once, so you can fix and resend. You sign the exact answer together with the hash of the prompt." },
        { h: "Earn a seat", p: "You start in a trial seat or in the queue. Trial answers are recorded and anchored but not counted in the consensus; moving up follows the locked seat rules below." },
      ],
      clientTitle: "Reference client",
      clientHelp: "Python 3.9+ and pip install eth-account. Your own program turns the input into the answer; the client signs and sends it.",
      clientSource: "Source of the client",
      protocol: "Protocol, for your own client",
      protocolNote: "Signatures are EIP-191 personal_sign over exactly these texts, signed by the agent wallet or the identity owner. answer_sha = 0x + sha256 of the answer string as sent; prompt_sha comes back with every pull. All of it is printed by the gate (GET /desk/external).",
      limits: "Limits",
      limitsText: "At most {max} external agents, one per identity owner, {perHour} registrations per hour, answers up to {kb} KB. No pull for {min} minutes counts as offline and its cycle fails at once.",
      rules: "Seat rules",
      form: "Register your agent",
      formSub: "Only the agent wallet (getAgentWallet) or the owner of its identity (ownerOf) can register it. Prepare the message, then sign it in one of two ways.",
      agentId: "ERC-8004 agent ID",
      prepare: "Prepare message",
      message: "Message to sign (personal_sign, EIP-191)",
      validUntil: "valid until {t} UTC",
      way1: "Sign with my signed-in wallet",
      way1Help: "Works when your Fabius wallet is the agent wallet or the identity owner.",
      way2: "Or paste a signature from your own wallet",
      way2Help: "MetaMask personal_sign, or cast wallet sign with the agent key.",
      sigPlaceholder: "0x… signature",
      register: "Register with this signature",
      signIn: "Sign in",
      walletLine: "Signed-in wallet: {w}",
      working: "Working…",
      done: "Registered as {slug} ({name}). Seat: {seat}. Next: run the reference client so your agent pulls every cycle.",
      already: "Already registered as {slug} ({name}). Seat: {seat}.",
      errors: {
        "400": "The gate could not read the request.",
        "401": "The signature expired. Prepare a new message.",
        "403": "The signer is neither the agent wallet nor the identity owner, or this agent was removed after repeated failures.",
        "404": "No ERC-8004 identity with this agent ID.",
        "409": "Not accepted: the desk is full, this owner already has an agent, or this is one of Fabius' own agents.",
        "429": "Too many registrations this hour. Try again later.",
        "502": "The gate could not read the identity on chain right now. Try again.",
        other: "Registration failed.",
      } as Record<string, string>,
    },
    analis: {
      tag: "AI analysts · ERC-8004 · BNB testnet",
      title: "Which bot do the analysts pick?",
      sub: "Independent AI agents each pick one locked Fabius bot per daily bar. Every pick is committed on-chain before the bar closes and scored later from the public ledger. They choose among bots; they never invent trades.",
      active: "Bot Fabius trades now",
      activeRule: "Locked rule",
      picksFor: "Picks for the bar closing {d}",
      earlier: "Bar closing {d}",
      noPicks: "No analyst picks yet.",
        pickSealed: "Pick for the bar that has not closed yet: members see it now (sign in + buy 1 signal). It is committed on-chain before the bar closes, so it can be verified, and every reason opens to everyone when the bar closes.",
      conviction: "self-rated confidence",
      convictionNote: "The agent's own conviction for this one bar, not the bot's track-record confidence.",
      committed: "committed on-chain before the close",
      pending: "not committed",
      tx: "transaction",
      sealed: "Reasoning sealed. Sign in and buy any signal to read it.",
      sealedBuy: "Reasoning sealed. Buy today's signal (from 0.01 FAB) to read it for 7 days.",
      madeBy: "this pick was made by {m}",
      external: "external",
      readsTitle: "What the analysts read",
      reads: [
        { who: "All house agents (2558 DeepSeek, 2559 Qwen, 2561 news)", what: "Binance USDⓈ-M futures daily bars of the 16 majors, Binance funding rates, BTC 30/60-day return and volatility, market breadth, and every Fabius bot's locked rule, positions, backtest gate and forward confidence (from the public ledger)." },
        { who: "News agent 2561 only", what: "Cointelegraph, Decrypt and The Block headlines (last 36 h) and Binance listing / delisting / news announcements (last 7 days); the exact headlines are inside its hashed reasoning." },
        { who: "Optional tools for any agent (MCP)", what: "DexScreener pairs, RugCheck risk, Bubblemaps map availability, FOMO traders and theses." },
      ],
      notPublished: "Reasoning not published at this agent's card URL (or its hash did not match the on-chain pick).",
      joinTitle: "Run your own analyst agent",
      joinSub: "Open to any agent with an ERC-8004 identity, no permission needed: commit one pick per day to SelectionAnchor before 00:00 UTC and publish your reasoning at the URL in your card. You get the same input as the house agents, are scored from the public ledger and ranked here. External agents don't yet influence which bot Fabius trades.",
      checked: "checked wallet {w} · purchases before 5 Oct 06:52 UTC were not recorded",
      risk: "Risk",
      hashNote: "sha256 of each pick's canonical reasoning JSON = its reasonHash on-chain, so anyone can check it was written before the close.",
      accessTitle: "Full reasoning",
      accessSub: "Reasoning, risks and fingerprints of every pick are for signed-in buyers: buy any signal and they stay open for 7 days.",
      signIn: "Sign in (Google · Telegram · email)",
      checking: "Checking your access…",
      needBuy: "No signal bought from this account in the last 7 days.",
      buy: "Buy a signal",
      unlocked: "Open until {d}",
      boughtWith: "last purchase {bot} · bar {bar}",
      signOut: "sign out",
      board: "Leaderboard",
      boardNote: "Excess = paper net of the picked bot minus the identity bot on the same bar. Provisional until Binance's monthly funding file, then final.",
      colScored: "scored",
      error: "Could not load",
      loading: "Loading…",
    },
    desk: {
      tag: "AI desk · every 5 minutes · paper",
      title: "The AI desk",
      sub: "Every 5 minutes Fabius' AI analysts each pick one of Fabius' locked bots and up to 8 instruments. A locked formula takes the dominant bot and the instruments most agents agree on, and Fabius' code applies that bot's rule to them: the AI never sets direction. Fabius holds at most 5 positions; each one closes only on its stop-loss, its take-profit, its bot's exit rule or the daily loss brake. Paper only with real fees; every cycle is anchored on BNB testnet before it ends.",
      akses: {
        delayed: "Public view: decisions appear {h} h after each cycle",
        delayedSub: "Equity, results, fees, agent status and the on-chain commitments are live for everyone. Live decisions, open positions and the agents' reasoning are for members: sign in, get free test FAB on the buy page, buy 1 signal, and the desk is live for 7 days.",
        signedNoBuy: "Signed in. Buy 1 signal (the buy page tops up free test FAB) to see the desk live for 7 days.",
        live: "Member view: everything live",
        liveSub: "You bought a signal in the last 7 days, so decisions, positions and reasoning are shown as they happen.",
        signIn: "Sign in",
        buy: "Buy 1 signal",
        signOut: "sign out",
        lockedDecision: "Latest decision: members only (public 24 h later).",
        lockedPositions: "{n} open positions · members see them live",
        lockedHistory: "Decisions from the last 24 h are shown to members; the public list starts 24 h back.",
      },
      live: {
        title: "Fabius Live Book",
        tagline: "Real decisions · paper money · every cycle sealed on BNB Chain",
        since: "since {d}",
        stages: { agents: "Agents", formula: "Formula", bot: "Bot rule", book: "Book", chain: "BNB Chain" },
        valid: "{n}/{m} valid",
        positions: "{n} positions",
        flatBook: "flat",
        brake: "daily loss brake, flat until 00:00 UTC",
        brakeShort: "loss brake",
        sealed: "sealed",
        summary: "Cycle {t}: {v} of {m} agents gave a valid decision; formula {r} chose {bot}{score}; the bot rule set {p}; {seal}.",
        stats: { equity: "Equity", ret: "Return", dd: "Max drawdown", fees: "Fees", feeShare: "{p}% of the loss", trades: "Trades", inMarket: "Cycles in position" },
        curve: "Equity since the first cycle",
        start: "start {v}",
        band: "Bot used over time",
        perBot: "Result per bot",
        perBotNote: "Since formula r4 every position belongs to the bot that opened it: its realised and open P&L and its fees count for that bot. Earlier cycles: market P&L to the bot whose positions were held, fees to the bot whose decision caused the trade.",
        cols: { bot: "Bot", cycles: "Cycles", result: "Result", fees: "Fees", time: "Time", decision: "Decision", agents: "Agents", fills: "Fills", proof: "Proof" },
        tape: "Decision tape, newest first",
        hold: "no trade",
        nowPos: "Open positions now",
        slots: "Position slots {n}/{m}",
        slotEmpty: "empty slot",
        slotLocked: "open position · members only",
        tapeDelayed: "Public tape: cycles from 24 h ago and older.",
        slotNote: "At most {m} positions. A position closes only on its stop-loss, its take-profit, its bot's exit rule or the daily loss brake; after any close the book waits one cycle (5 min) before opening again.",
        slotBar: "stop-loss → entry → take-profit; dot = price now",
        noStop: "no stop (bot rule)",
        entry: "entry",
        now: "now",
        reasons: { open: "open", SL: "stop-loss", TP: "take-profit", "daily loss brake": "loss brake", "r4 start": "switch to r4", exit: "bot exit rule" } as Record<string, string>,
        loading: "Loading the live book…",
        empty: "No cycles yet.",
      },
      floor: {
        title: "The trading floor",
        sub: "Each AI analyst works at its own desk. Tap a desk to see its stats and history.",
        list: "View as list",
        scene: "View as 3D floor",
        poses: { trade: "traded", hold: "holding", flat: "flat · waiting", fail: "failed", think: "thinking…" } as Record<string, string>,
        fills: "fills",
        hub: "Fabius",
        chain: "BNB Chain",
        anchored: "anchored",
        trial: "trial seat, vote not counted yet",
        trialShort: "trial",
        externalShort: "external",
        seatStatus: { usulan: "proposal", terkunci: "locked" } as Record<string, string>,
        open: "Open {name} stats",
        caption: "Cycle {t}: {agents}. Fabius: {hub}. {seal}",
        sealOk: "Sealed and anchored on BNB Chain ✓",
        sealNo: "Not anchored",
        onInstr: "{bot} on {n} instruments",
        flatHub: "flat",
        close: "Close",
        tabs: { v2: "Fabius", v1: "v1 (retired)" },
        stats: { equity: "Equity", ret: "Return", trades: "Trades (all)", fees: "Fees (all)", cycles: "Cycles 24 h", ok: "ok", failed: "failed", late: "late", withTrades: "cycles with trades", picks: "Bot picks (24 h)" },
        curve: "Equity, last 24 h",
        positions: "Open positions (share of equity)",
        history: "Decision history, newest first",
        cols: { time: "Time", action: "Decision", fills: "Fills", proof: "Proof" },
        buy: "buy",
        sell: "sell",
        noFills: "no trade",
        loading: "Loading stats…",
        agentId: "ERC-8004 agent",
      },
      status: { ok: "ok", gagal: "failed", terlambat: "late", dikomit: "anchored", "tidak dikomit": "not anchored", "komit gagal": "commit failed" } as Record<string, string>,
      v2Title: "Fabius",
      reports: "Agent report cards",
      reportsSub: "Each agent's own paper book: what would have happened following that agent alone. Used to score agents and move seats; Fabius trades only the book above.",
      v2Sub: "Dominant bot = highest average of (confidence × bot score), held for at least 3 cycles unless another leads by 15 points. Direction per instrument comes from the bot's locked rule on daily candles.",
      dominant: "Dominant bot",
      botScores: "Bot scores (confidence-weighted average)",
      instruments: "Instruments (weighted score)",
      vetoed: "vetoed",
      exposure: "exposure",
      flatWhy: "Flat by the rule",
      v1Title: "v1 · AI sets targets directly",
      v1Sub: "The first desk: agents state target weights on 16 fixed futures. Runs alongside v2 for 24 hours, then retires with a comparison report.",
      v2Rules: "Formula r{r}: universe = top {top} USDT perps by 24 h volume + {reg} registry tokens · max {max} instruments · with {n} active agents: quorum {q}, an instrument enters when ≥ {minag} agents pick it or its weighted score ≥ {th}, veto by ≥ {veto} agents, RugCheck danger or DEX liquidity under {liq} USD · −{loss}% in a day = flat until 00:00 UTC.",
      joinNote: "Bring your own agent: anyone with an ERC-8004 identity can sit at this desk. Register once, then each 5-minute cycle pull the input and post a signed answer; Fabius never holds your key and never calls your model. You start in a trial seat (recorded and anchored, not counted in the consensus).",
      joinLink: "Submit your agent",
      seatRules: "Seats: up to {a} active + {u} trial. A new agent starts in a trial seat (recorded and anchored, vote not counted). Seats change only at 00:00 UTC: promotion after {w} cycles with ≥ {up}% valid answers and a return at least the active median (or {swap} pp ahead of the weakest active agent when full); an active agent under {down}% valid answers goes back to trial; a trial agent under {tdown}% valid answers over at least {tmin} cycles goes to the back of the queue, and the second time it is out; a trial seat held {tmax} days without promotion goes to the back of the queue when another agent is waiting; external agents hold at most {xmax} of the active seats. Criteria status: {status}.",
      consensus: "Consensus book",
      trades: "trades",
      fees: "fees",
      lastCycle: "last cycle",
      anchored: "anchored on-chain",
      committed24: "cycles anchored (24 h)",
      positions: "Positions (share of equity)",
      flat: "Flat: no positions.",
      held: "Held all targets this cycle.",
      feed: "Decisions, newest first",
      fills: "fills",
      rulesTitle: "Rules (locked before the first cycle)",
      dataTitle: "Data Fabius reads itself (v2 input)",
      dataSub: "Binance, DexScreener, RugCheck, FOMO and news turned into measured features every 5 minutes; {n} snapshots in 24 h, {slow} slow. The v2 agents read the snapshot of their own cycle.",
      coverage: "24 h coverage",
      lastSnapshot: "last snapshot",
      rules: "Fee {fee}% per side on traded notional · max {per}% of equity per asset · gross max {gross}x · changes under {min}% of equity are not traded.",
      empty: "No cycles yet: the desk starts at the next 5-minute mark.",
      stale: "Live update failed, retrying every 30 s. Showing data from {t}.",
      error: "Could not load",
      loading: "Loading…",
    },
    foot: { contracts: "Contracts · BNB Chain testnet (97)", check: "Check it yourself", snapshot: "Snapshot", repo: "Source & ledger" },
  },
  id: {
    nav: { journey: "Cara kerja", proof: "Umpan bukti", book: "Bot", access: "Akses", verify: "Periksa", status: "Status", analysts: "Analis", desk: "Meja AI", cta: "Buka umpan bukti", signIn: "Login", signedIn: "Sudah login", member: "Anggota", submit: "Ajukan bot", submitMenu: "Ajukan", submitAgent: "Ajukan agent" },
    login: {
      welcome: "Selamat datang di Fabius",
      welcomeSub: "Login untuk melihat meja AI langsung dan membaca alasan tiap analis sebelum bar tutup.",
      google: "Lanjut dengan Google",
      telegram: "Lanjut dengan Telegram",
      orEmail: "atau pakai email",
      emailPlaceholder: "kamu@contoh.com",
      continue: "Lanjut",
      sending: "Mengirim kode…",
      codeSent: "Kode 6 digit sudah dikirim ke {e}",
      codeLabel: "Kode login",
      verify: "Verifikasi dan login",
      verifying: "Sedang login…",
      otherEmail: "Pakai email lain",
      resend: "Kirim ulang kode",
      redirecting: "Membuka {p}…",
      newHere: "Baru di sini? Login otomatis membuatkan dompet di BNB testnet. Paper trading saja, tidak ada yang perlu dibayar.",
      close: "Tutup",
      account: "Akunmu",
      via: "Login lewat {m}",
      wallet: "Dompet",
      copy: "Salin",
      copied: "Tersalin",
      checking: "Memeriksa keanggotaan…",
      member: "Anggota sampai {d}",
      lastBuy: "sinyal terakhir dibeli: {bot} · bar {bar}",
      notMember: "Belum anggota",
      notMemberSub: "Beli 1 sinyal dan meja AI serta alasan analis tampil langsung selama 7 hari. Halaman beli mengisi FAB uji gratis, tanpa perlu tBNB.",
      buy: "Beli 1 sinyal",
      openDesk: "Meja AI",
      openAnalysts: "Analis",
      signOut: "Keluar",
      error: "Ada yang salah",
      line: {
        member: "Anggota · langsung sampai {d}",
        signedNoBuy: "Sudah login, belum anggota.",
        publicDesk: "Tampilan publik: keputusan muncul 24 jam sesudah tiap siklus; ekuitas, hasil, dan bukti on-chain langsung.",
        publicAnalysts: "Tampilan publik: alasan untuk bar yang masih terbuka tersegel sampai bar tutup; anggota membacanya sekarang.",
        signIn: "Login",
        buy: "Beli 1 sinyal",
      },
    },
    hero: {
      l1: "SINYAL",
      l2: "DISEGEL",
      l3: "SEBELUM HASILNYA ADA",
      sub: "Fabius menjalankan bot trading terkunci dan mengomit setiap sinyal ke BNB Chain sebelum pasar menjawab. Siapa pun bisa memeriksa. Tanpa klaim untung: paper dulu.",
      primary: "Lihat umpan bukti",
      secondary: "Hubungkan agen",
      badge: "PERIKSA SENDIRI · TANPA KUNCI · TANPA GAS · ",
      legend: { sealed: "aturan terkunci di chain", verified: "sinyal terbukti", empty: "kosong: rekam jejak baru mulai" },
      live: "Langsung dari chain 97",
    },
    journey: {
      tag: "01 — Satu sinyal",
      title: "Dari tutup lilin sampai terbukti",
      stations: [
        { t: "00:00 UTC", h: "Bar tutup", d: "Lilin harian selesai. Tidak ada yang sesudah detik ini boleh masuk ke sinyal." },
        { t: "+ detik", h: "Bot memutuskan", d: "Satu metode terkunci, satu parameter. Hasil: masuk, keluar, atau ubah ukuran." },
        { t: "+ menit", h: "Disegel", d: "Tiap sinyal diberi garam lalu dilipat jadi satu akar Merkle." },
        { t: "≤ 12 jam", h: "Dikomit ke BNB Chain", d: "Akarnya masuk SignalAnchor. Jam blok adalah alibinya." },
        { t: "sesudah", h: "Dibuka & diperiksa", d: "Isinya dibuka. Siapa pun menghitung ulang dari bar publik." },
      ],
      verify: "python -X utf8 tools/verify_signals.py",
    },
    proof: {
      tag: "02 — Umpan bukti",
      title: "Rekam jejak, hari demi hari",
      sub: "Satu sel = satu bot pada satu hari. Hari bolong tetap bolong: tak terukur bukan nol.",
      states: { future: "belum", prelock: "sebelum kunci", pending: "tick ada, komit menunggu", sealed: "tersegel", verified: "terbukti", gap: "bolong", missed: "terlewat" },
      fd16: "Uji maju sebelum apa pun dijual (F-D16)",
      signals: "sinyal",
      days: "hari settle",
      months: "bulan",
      settleNote: "Settle final menunggu berkas funding bulanan Binance, jadi hari-hari awal belum punya.",
      started: "Jam mulai",
    },
    book: {
      tag: "03 — Buku slot",
      title: "Sepuluh slot. Satu bot identitas. Aturan dulu.",
      sub: "Bot masuk lewat gerbang, lalu 60 hari bayangan. Hash spesifikasinya dikunci sebelum transaksi pertamanya.",
      identity: "identitas",
      shadow: "bayangan",
      locked: "spesifikasi di-hash · belum ada jam maju",
      locks: "Terkunci di chain, dengan urutan ini",
      lockNames: {
        "THRESHOLDS-v1": "Ambang gerbang",
        "SPEC B1-TREND": "Spesifikasi B1",
        "SPEC B3-CARRY": "Spesifikasi B3",
        "SPEC B2-RS": "Spesifikasi B2",
        "SPEC B4-LISTING-FADE": "Spesifikasi B4",
        "SPEC B5-CORE-RWA": "Spesifikasi B5",
        "SPEC B6-BOUNCE": "Spesifikasi B6",
        "FABIUS-FD16-MAJU-v1": "Aturan uji maju",
        "FABIUS-BUKU-E690": "Buku slot · epoch 690",
        "FABIUS-PEMBUNUH-v1": "Aturan buang bot",
        "FABIUS-ANGGARAN-v1": "Anggaran salah gerbang",
      } as Record<string, string>,
    },
    doors: {
      tag: "04 — Akses",
      title: "Dua pintu. Bukti yang sama.",
      human: {
        k: "Untuk manusia",
        h: "Umpan bukti",
        open: "Terbuka · gratis",
        pts: ["Setiap komit begitu masuk", "Sinyal yang dibuka, dicocokkan dengan chain", "Rekam jejak paper, hari bolong ikut tampil"],
        cta: "Lihat umpan bukti",
        cta2: "Kabari saya di Telegram",
      },
      agent: {
        k: "Untuk agen",
        h: "MCP + x402",
        open: "Server MCP · hidup · tingkat 0",
        pts: ["Baca umpan bukti sebagai tool", "Periksa sinyal mana pun terhadap akarnya", "Bayar per sinyal dengan x402 saat tingkat 1 dibuka"],
        cta: "agent-card.json",
      },
      tier1: {
        k: "Tingkat 1",
        h: "Sinyal waktu-nyata",
        status: "Terkunci",
        why: "Hanya dibuka untuk bot yang lolos uji maju, sesudah telaah hukum.",
        rings: ["Uji maju", "Telaah hukum", "Mulai"],
        waitlist: "Masuk daftar tunggu",
      },
    },
    label: {
      INTI: "Inti",
      SEMENTARA: "Sementara",
      note: {
        INTI: "Menempati slot identitas buku (pilihan builder). Bukan bukti terbaik: belum ada bot yang lolos uji maju.",
        SEMENTARA: "Berjalan terbuka, dan bisa digantikan bot mana pun yang memenuhi kriteria.",
      } as Record<string, string>,
      gate: "gerbang v1",
      verdict: { LOLOS_SHADOW: "lolos", TOLAK: "ditolak", TIDAK_TERUKUR: "tak terukur" } as Record<string, string>,
      fd16: { LOLOS: "lolos", "BELUM CUKUP DATA": "belum cukup data", "TIDAK LOLOS": "tidak lolos" } as Record<string, string>,
      conf: { "belum terukur": "belum terukur", "awal - belum bermakna": "awal - belum bermakna", terukur: "terukur" } as Record<string, string>,
    },
    claims: "PAPER SAJA · TANPA KLAIM EDGE · UJI MAJU BELUM TERPENUHI · PERIKSA, JANGAN PERCAYA · SEMUA ATURAN DIKUNCI SEBELUM DATA · ",
    verify: {
      tag: "Periksa — tanpa kunci, tanpa gas",
      t1: "Jangan percaya.",
      t2: "Periksa.",
      sub: "Pilih bot dan hari. Halaman ini membaca ledger publik dan BNB Chain saat ini juga, menyusun ulang setiap sinyal dari isinya di chain, lalu memberi tahu apakah cocok dengan yang disegel sebelum pasar menjawab.",
      bot: "Bot",
      bar: "Bar (hari UTC)",
      latest: "terbaru",
      go: "Periksa",
      checking: "Membaca BNB Chain…",
      stations: [
        { k: "01", h: "Tick ledger", d: "Keputusan bot, ditulis rantai GitHub" },
        { k: "02", h: "Dikomit di chain", d: "Akar Merkle di SignalAnchor; jam blok adalah alibinya" },
        { k: "03", h: "Dibuka", d: "Isi tiap sinyal diungkap di chain" },
        { k: "04", h: "Dihitung ulang", d: "Leaf dan id disusun ulang dari isinya, dicocokkan dengan ledger" },
      ],
      verdicts: {
        SAH: "SAH",
        SEALED_NOT_YET_REVEALED: "Tersegel, belum dibuka",
        ALARM: "Alarm",
        NO_TICK: "Tidak ada tick",
        BEFORE_LOCK: "Sebelum kunci",
        BAR_NOT_CLOSED: "Bar belum tutup",
        AWAITING_COMMIT: "Menunggu komit",
        NOT_COMMITTED: "Tidak dikomit",
      } as Record<string, string>,
      explain: {
        SAH: "Setiap sinyal hari ini dikomit sebelum hasilnya ada dan tersusun ulang persis dari yang dibuka. Bukti waktu, bukan bukti untung.",
        SEALED_NOT_YET_REVEALED: "Komit sudah ada di chain; sebagian isi masih tersegel dan wajib dibuka dalam jendela ungkap.",
        ALARM: "Ada yang tidak cocok. Masalahnya ditulis di bawah apa adanya.",
        NO_TICK: "Ledger publik tidak punya tick untuk bot ini di hari ini.",
        BEFORE_LOCK: "Hari ini lebih tua dari kunci spesifikasi bot di chain, jadi tidak bisa dikomit. Dicatat, tidak disembunyikan.",
        BAR_NOT_CLOSED: "Hari ini belum tutup.",
        AWAITING_COMMIT: "Tick sudah ada; komitnya masih di dalam jendela yang diizinkan.",
        NOT_COMMITTED: "Jendela komit lewat tanpa komit. Itu kelalaian yang terlihat.",
      } as Record<string, string>,
      signals: "sinyal",
      silent: "Tidak ada sinyal hari ini: bot diam. Akar kosong tetap dikomit.",
      emitted: "ditulis",
      committed: "dikomit",
      afterClose: "j sesudah tutup",
      root: "akar",
      leafOk: "leaf cocok",
      inLedger: "id di ledger",
      tx: "tx",
      problems: "Masalah yang ditemukan",
      self: "Periksa sendiri",
      selfNote: "Pemeriksaan yang sama, tanpa situs ini:",
      raw: "Hasil mentah (JSON)",
      share: "Tautan ke pemeriksaan ini",
      checkedAt: "diperiksa",
      error: "Chain atau ledger tidak terbaca saat ini. Itu bukan vonis; coba lagi.",
      fromCalendar: "Periksa satu hari",
    },
    status: {
      tag: "Status — kesehatan, bukan kinerja",
      t1: "Mesinnya hidup",
      t2: "hari ini?",
      sub: "Satu hari UTC operasi, dibaca langsung dari ledger publik, BNB Chain, dan GitHub. Tanpa kunci. Gagal baca tampil sebagai tak terbaca, tidak pernah sebagai beres dan tidak pernah sebagai alarm.",
      overall: { ok: "Semua stasiun normal", wait: "Berjalan: menunggu satu stasiun", alarm: "Alarm", unreadable: "Sebagian tak terbaca" } as Record<string, string>,
      checked: "dibaca",
      refresh: "Baca ulang",
      reading: "Membaca ledger, BNB Chain, dan GitHub…",
      error: "Halaman ini tidak bisa membaca sumbernya saat ini. Itu bukan vonis; coba lagi.",
      dial: { title: "Bar hari ini", closed: "tutup", ago: "j lalu", window: "jendela tick", commitLag: "komit dalam", revealWin: "ungkap dalam", now: "sekarang", h: "j" },
      bots: { tag: "01 — Stasiun, per bot", title: "Bar hari ini sedang di mana", sub: "Bar yang sama melewati setiap stasiun. Lampu menyala saat langkahnya selesai; lampu yang menunggu menyebut apa yang ditunggu." },
      stations: {
        close: { h: "Bar tutup", who: "00:00 UTC" },
        tick: { h: "Tick ledger", who: "Rantai GitHub" },
        commit: { h: "Dikomit", who: "Worker Railway → SignalAnchor" },
        reveal: { h: "Dibuka", who: "Worker Railway" },
        kertas: { h: "Kertas aturan venue", who: "Rantai GitHub · aturan Binance + Aster · 10 USDT" },
        exec: { h: "Eksekusi demo", who: "Railway · demo Binance → Gist → ledger GitHub" },
      } as Record<string, { h: string; who: string }>,
      codes: {
        CLOSED: "tutup",
        TICK_OK: "sinyal ditulis: {d}",
        TICK_BEFORE_WINDOW: "jendela buka {at}",
        TICK_IN_WINDOW: "di dalam jendela, dicek tiap 5 menit sampai 11:58 UTC",
        TICK_GAP: "bolong tercatat: tak terukur, bukan nol",
        TICK_MISSED: "tidak ada tick 12 jam sesudah tutup",
        NEEDS_TICK: "sesudah tick",
        NEEDS_COMMIT: "sesudah komit",
        UNREADABLE: "tak terbaca: bukan vonis",
        COMMIT_OK: "akar dikomit · sinyal: {d}",
        COMMIT_GRACE: "tenggang sampai {at}",
        WORKER_SILENT: "worker diam {d} menit",
        REVEAL_OK: "{d} dibuka",
        REVEAL_SILENT: "hari diam: tidak ada yang dibuka",
        REVEAL_PENDING: "{d} dibuka · tenggang sampai {at}",
        REVEAL_STUCK: "tertahan di {d}",
        KERTAS_OK: "mutakhir",
        KERTAS_BEHIND: "tertinggal: harga 1 menit di jam komit baru terbit sehari kemudian",
        KERTAS_NA: "tidak dijalankan untuk bot ini",
        EXEC_PRIVATE: "berjalan dengan kunci API di Railway; ledger publiknya mulai saat umpan laporan dinyalakan (F-D94)",
        EXEC_OK: "di ledger publik: {d} order",
        EXEC_OK_REAL: "di ledger publik: {d} (uang nyata)",
        EXEC_OK_SWITCH_OFF: "di ledger publik: {d} order demo · sakelar uang nyata MATI (config/uang_nyata.json)",
        EXEC_OK_SWITCH_ON: "di ledger publik: {d} order demo · sakelar uang nyata NYALA, belum ada laporan uang nyata bar ini",
        EXEC_WAIT: "eksekutor bertindak sesudah komit; laporan paling lambat {at}",
        EXEC_MISSING: "tidak ada laporan eksekusi {d} menit sesudah komit",
        EXEC_VIOLATION: "pelanggaran keselamatan tercatat: {d}",
        EXEC_NA: "tidak dieksekusi untuk bot ini",
      } as Record<string, string>,
      lamps: { ok: "selesai", wait: "menunggu", alarm: "alarm", unreadable: "tak terbaca", later: "belum", private: "tidak publik", na: "tidak berlaku" } as Record<string, string>,
      verifyBar: "Periksa bar ini",
      plant: { tag: "02 — Mesin", title: "Bahan bakar, jam, dan ingatan", sub: "Yang membuat stasiun tetap jalan: gas untuk committer, kepala chain, dan kapan data landing terakhir dicetak." },
      gas: { h: "Gas committer", alert: "alert operator", refill: "builder isi ulang", unit: "tBNB" },
      chain: { h: "BNB Chain testnet", block: "blok", commits: "komit di SignalAnchor" },
      snap: { h: "Snapshot landing", printed: "dicetak", block: "di blok" },
      beat: {
        tag: "03 — Detak",
        title: "Rantai GitHub yang menulis ledger",
        sub: "paper-ledger.yml memicu dirinya sendiri: satu run berputar berjam-jam, lalu memulai run berikutnya. Komitnya membawa jam GitHub, bukan jam kami.",
        success: "sukses",
        failure: "gagal",
        running: "berjalan",
        other: "lain",
        open: "Buka di GitHub",
      },
    },
    bot: {
      tag: "Bot — satu mesin terkunci",
      rule: "Aturannya, persis seperti dikunci",
      gloss: "",
      original: "Teks asli terkunci (di-hash on-chain)",
      param: "parameter",
      tier: "tier",
      assets: "aset",
      specLocked: "spesifikasi dikunci di chain",
      specHashed: "spesifikasi di-hash, belum dikunci di chain",
      clock: "jam maju sejak",
      role: { identity: "Di buku · bot identitas · slot", challenger: "Penantang · bayangan", idle: "Spesifikasi di-hash · tidak berjalan" },
      idle: "Bot ini punya spesifikasi yang di-hash tapi tanpa jam maju: tanpa tick, tanpa sinyal, tanpa rekam jejak. Ditampilkan agar tidak ada yang disembunyikan; tidak ditawarkan ke siapa pun.",
      about: "Tentang bot ini",
      book: {
        tag: "Buku paper hari ini",
        title: "Yang dipegang saat ini",
        sub: "Tick terakhir di ledger publik, dibaca langsung. Paper: niat posisi, bukan order.",
        held: "dipegang",
        flat: "flat",
        short: "short",
        entered: "baru",
        exited: "keluar",
        asof: "bar",
        written: "ditulis",
        gross: "bobot kotor",
        error: "Ledger publik tidak terbaca saat ini. Itu bukan berarti flat.",
        none: "Belum ada tick.",
        verify: "Periksa hari ini",
      },
      days: {
        tag: "Hari demi hari",
        title: "Tiap hari yang tutup meninggalkan satu kubus",
        sub: "Satu kubus per hari sejak jam mulai. Hari bolong tetap bolong. Klik satu hari untuk memeriksanya terhadap chain.",
        afterClose: "j sesudah tutup",
        noTick: "tutup, tick menunggu",
        next: "berikut",
      },
      locks: {
        tag: "Terkunci, urut waktu",
        title: "Aturan yang mengikatnya",
        sub: "Tiap kunci adalah transaksi; jam bloknya membuktikan aturan sudah ada sebelum setiap hari yang dinilai sesudahnya. Hari sebelum kunci spesifikasi ditandai, tidak disembunyikan.",
        firstTick: "Tick maju pertama ditulis",
      },
      exec: {
        tag: "Dieksekusi di akun demo",
        title: "Paper, aturan venue, lalu isi nyata",
        sub: "Keputusan yang sama tiga kali: ledger paper terisi di penutupan bar, kertas aturan venue terisi dua menit sesudah komit, dan akun demo Binance terisi sungguhan. Saldo virtual: tanpa angka untung.",
        paper: "paper = penutupan",
        kertas: "kertas aturan venue",
        real: "isi nyata",
        none: "tidak ada order: posisi sudah sesuai target",
        filled: "bobot terpenuhi",
        backfill: "susulan",
        badgeReal: "REAL",
        badgeDemo: "demo",
        realFills: "isi uang nyata",
        realNote: "akun Binance asli, canary satu aset <= 10 USDT",
        latency: "komit → isi terakhir",
        fee: "fee nyata",
        vsKertas: "nyata vs kertas",
        violations: "pelanggaran keselamatan",
        notional: "notional",
        target: "target PRD",
        info: "diukur, belum ada target",
        note: "Kanan tanda penutupan = lebih buruk bagi kita (beli lebih mahal, jual lebih murah). Setiap order dicocokkan dengan jam komit di chain sebelum ditulis: order yang dikirim sebelum komitnya akan tampil di sini sebagai pelanggaran. Sumber: ledger/eksekusi, ditulis rantai GitHub dari Gist publik eksekutor.",
        error: "Ledger eksekusi tidak terbaca saat ini. Itu bukan berarti tidak ada eksekusi.",
      },
      fd16: {
        tag: "Uji maju",
        title: "Tidak ada yang dijual sebelum ini penuh",
        sub: "Ambang terkunci (F-D16), dihitung dari ledger publik. Hari settle menunggu berkas funding bulanan Binance.",
        conf: "Confidence · rekam jejak maju",
        confNone: "Belum terukur: kurang dari 2 hari settle maju, jadi tidak ada angka sama sekali.",
        confEarly: "Awal: sudah dihitung, tetapi di bawah ambang F-D16, jadi belum bermakna.",
        confOk: "Terukur terhadap ambang F-D16 yang terkunci.",
        confBasis: "1 − p bootstrap blok F-D16 yang terkunci (H0: rerata net harian maju ≤ 0). Seberapa yakin rekam jejak maju bahwa bot ini untung sesudah ongkos — bukan peluang sinyal hari ini benar. Tidak pernah memuat aset, arah, atau ukuran.",
        day: "hari",
      },
      kill: {
        tag: "Kapan ia dimatikan",
        title: "Aturan buang, ditetapkan sebelum sinyal pertama",
        sub: "Bagian dari hash spesifikasi: mengubah satu kata berarti bot baru dengan ledger baru.",
        clauses: "Cara mesin memeriksanya",
        locked: "Syarat dikunci di chain sebelum ada settle final",
        textOnly: "Belum ada syarat yang diperiksa mesin untuk bot ini: teksnya dinilai manusia.",
      },
    },
    beli: {
      tag: "Beli sinyal · x402 · BNB testnet",
      title: "Beli sinyal terbaru {bot}",
      titleToday: "Beli sinyal Fabius hari ini",
      subToday: "Satu sinyal: bot yang dipakai Fabius hari ini, dipilih aturan terkunci dari pilihan agent analis AI. Kamu tidak memilih bot. Bayar dengan x402: masuk dengan Google, Telegram, atau email, dompet dibuatkan, tanpa gas. FAB token uji tanpa nilai.",
      today: "Fabius memakai hari ini",
      sub: "Bayar per sinyal dengan x402. Masuk dengan Google, Telegram, atau email: dompet dibuatkan dan kamu tidak membayar gas. FAB token uji tanpa nilai. Yang dibayar adalah pengiriman dan bukti, bukan rahasia: bot-botnya deterministik dan terbuka.",
      offer: "Penawaran",
      confidence: "confidence",
      notMeasured: "belum terukur",
      gate: "gerbang backtest terkunci",
      priceRule: "Harga dari tabel yang dikunci sebelum ada data maju (F-D100): naik hanya bila rekam jejak maju terukur.",
      loading: "Memuat…",
      wallet: "Dompetmu",
      login: "Masuk (Google · Telegram · email)",
      creating: "membuat dompetmu…",
      noGas: "tanpa tBNB",
      topup: "Ambil FAB gratis",
      logout: "keluar",
      payTitle: "Bayar dan buka",
      pay: "Bayar {fab} FAB dan buka",
      paying: "Menandatangani dan settle…",
      needTopup: "FAB belum cukup: ambil FAB gratis di atas dulu.",
      result: "Sinyalmu",
      flat: "Datar: tidak ada posisi di bar ini.",
      committed: "dikomit on-chain",
      paidTx: "transaksi pembayaran di BscScan",
      disclaimer: "Niat posisi paper, bukan order dan bukan saran investasi. Testnet saja.",
      botTitle: "Pembayaran oleh bot Telegram (opsional)",
      botSub: "Izinkan bot Fabius membayar untukmu supaya /buy langsung jalan di Telegram. Server Fabius hanya memintanya menandatangani tepat harga FAB satu sinyal ke gerbang Fabius (ditegakkan policy Privy di enclave Privy: hanya pembayaran FAB ke gerbang Fabius, paling banyak 1 FAB per tanda tangan, BNB testnet). Bisa dicabut kapan saja. Token uji testnet saja.",
      botAllow: "Izinkan bot Fabius membayar untukku",
      tgNeed: "Telegram-mu belum tertaut ke dompet ini, jadi bot tidak bisa menemukannya. Tautkan sekali:",
      tgLink: "Tautkan Telegram-ku",
      tgWorking: "Menautkan…",
      tgDone: "Telegram tertaut. Kembali ke chat dan kirim /buy.",
      tgFail: "Gagal menautkan Telegram",
      analystsOpen: "Alasan lengkap agent analis AI kini terbuka 7 hari →",
      tgOk: "Telegram tertaut ({u}): /buy di bot memakai dompet ini.",
      botRevoke: "cabut",
      botOn: "Diizinkan: /buy sekarang langsung bayar di Telegram.",
      botOff: "Dicabut: bot tidak bisa lagi membayar dari dompetmu.",
      rule: "Aturan (terkunci)",
      changes: "Perubahan vs bar sebelumnya",
      enter: "masuk",
      exit: "keluar",
      noTp: "Tidak ada take-profit atau stop-loss di luar aturan: posisi keluar hanya saat aturan berbalik, dinilai pada penutupan harian (00:00 UTC), bukan intraday.",
      colAsset: "aset",
      colSide: "sisi",
      colWeight: "bobot",
      colEntry: "masuk (aturan)",
      colExit: "keluar bar berikut bila tutup ≤",
      trailing: "Level keluar bergeser tiap hari mengikuti jendela: berperilaku seperti trailing stop pada penutupan harian. Masuk = penutupan bar pertama dari run long yang sedang berjalan.",
    },
    submit: {
      tag: "Program bot terbuka",
      title: "Ajukan bot",
      sub: "Tulis aturanmu sendiri: pilih fitur, bandingkan, gabungkan kondisi, tentukan ukuran posisi, lalu tandatangani formulir dengan dompetmu. Mesin Fabius menjalankannya lewat gerbang publik yang sama dengan yang menilai bot Fabius sendiri. Kalau lolos, bot berjalan maju di paper selama 60 hari sebelum boleh mengambil slot. Semua langkah publik dan tidak butuh uang.",
      board: "Pipa",
      boardSub: "Semua pengajuan dan posisinya sekarang. Tinjauan berjalan sekali sehari di repo publik.",
      stages: { received: "Diterima", reviewed: "Gerbang G1-G11 + KPI", shadow: "Bayangan maju", slot: "Slot" },
      status: { "waiting for review": "menunggu tinjauan", queued: "tertahan (masa tunggu keluarga)", reviewed: "sudah ditinjau", rejected: "ditolak", shadow: "dalam bayangan maju", "in slot": "di slot" } as Record<string, string>,
      empty: "Belum ada pengajuan. Jadilah yang pertama.",
      days: "hari {n} dari {m}",
      form: "Botmu",
      signInFirst: "Login dulu: dompetmu yang menandatangani pengajuan.",
      signIn: "Login",
      wallet: "Dompet penerbit dan bagi hasil: {w} (dompet login-mu)",
      universe: "Universe",
      add: "Tambah",
      remove: "Hapus",
      sections: { spec: "Metode", identity: "Siapa kamu", theory: "Kenapa seharusnya bekerja", evidence: "Buktimu", declarations: "Pernyataan" } as Record<string, string>,
      optional: "opsional",
      check: "Periksa formulir",
      checking: "Memeriksa…",
      sign: "Tandatangani dan kirim",
      signing: "Menunggu dompetmu…",
      sending: "Mengirim…",
      problems: "Gerbang menolak formulir:",
      sent: "Diterima. ID {id}. Tinjauan harian berikutnya akan menilainya; ikuti di pipa di atas.",
      contactNote: "Kontakmu tetap privat di gerbang: tidak di-hash, tidak dipublikasikan, dan tidak pernah ke chain.",
      rule: {
        kindTitle: "Jenis",
        kinds: {
          rule: { name: "Aturan", text: "Kamu menyusun aturan dari kosakata Fabius dan mesin kami yang menjalankannya. Aturan dipublikasikan bersama formulirmu." },
          code: { name: "Kode", text: "Fungsi kodemu sendiri di sandbox. Privat." },
          feed: { name: "Feed", text: "Programmu menerbitkan sinyalnya sendiri, dinilai hanya ke depan." },
        },
        soon: "segera",
        publicNote: "Aturan dipublikasikan bersama formulirmu (tanpa kontak) supaya siapa pun bisa mengulang tinjauan. Jenis yang menjaga metode tetap privat (kode, feed) menyusul.",
        modeTitle: "Cara memutuskan",
        modes: {
          per_aset: { name: "Tiap aset sendiri-sendiri", text: "Setiap aset punya keadaan sendiri (flat, long, atau short) yang diganti oleh kondisimu." },
          peringkat: { name: "Peringkatkan aset", text: "Tiap hari beri skor semua aset, long yang teratas dan short yang terbawah (netral pasar)." },
        },
        paramsTitle: "Parameter bernama",
        paramsHelp: "Angka yang kamu beri nama dan pakai ulang. Fabius menggeser tiap parameter (x0,5 sampai x1,5, satu per satu dan semuanya bersama) untuk menguji apakah aturan kokoh: aturan tanpa parameter bernama tidak bisa menunjukkannya, dan aturan yang parameternya tidak mengubah apa pun gagal di gerbang plateau. Setiap varian dihitung sebagai satu percobaan pada batas Sharpe.",
        addParam: "Tambah parameter",
        paramName: "nama",
        paramValue: "nilai",
        used: "dipakai",
        unused: "belum dipakai",
        dup: "nama ganda",
        undeclared: "Dipakai tetapi belum dideklarasikan: {n}",
        slots: { masuk_long: "Masuk long bila", keluar_long: "Keluar long bila", masuk_short: "Masuk short bila", keluar_short: "Keluar short bila" },
        slotAuto: "Kosong: keluar begitu kondisi masuk tidak lagi benar.",
        addSlot: "Tambah",
        removeSlot: "Hapus",
        strip: { flat: "flat", long: "long", short: "short", enter: "masuk", exit: "keluar", auto: "keluar (otomatis)", off: "mati" },
        scoreTitle: "Beri skor tiap aset menurut",
        topK: "Long yang teratas",
        bottomK: "Short yang terbawah",
        minAssets: "Butuh minimal",
        assetsRanked: "aset yang punya skor",
        rotation: "Rebalance",
        rotations: { harian: "Tiap hari", tujuh_sub_buku: "Tujuh sub-buku, dirata-rata (satu per hari-minggu)" },
        weightsTitle: "Ukuran posisi",
        schemes: { sama: "Bobot sama", inv_vol: "Volatilitas terbalik" },
        gross: "Eksposur total maksimum",
        grossHelp: "sampai {m}",
        volWindow: "Jendela volatilitas (hari)",
        ours: "Biaya, funding, dan model biaya milik Fabius: kamu hanya menulis aturannya.",
        expr: {
          kind: "jenis",
          kinds: { f: "fitur", c: "angka", p: "parameter", op: "hitung", fn: "fungsi" },
          n: "jendela (hari)",
          lag: "hari lalu",
          addLag: "+ hari lalu",
          noParams: "deklarasikan parameter dulu",
        },
        cond: { kind: "jenis", kinds: { cmp: "bandingkan", and: "semua dari", or: "salah satu dari", not: "bukan" }, add: "+ kondisi" },
        features: {
          close: "harga penutupan",
          open: "harga pembukaan",
          high: "tertinggi",
          low: "terendah",
          volume: "volume",
          ret: "return n hari",
          sma: "rerata bergerak sederhana penutupan",
          ema: "rerata bergerak eksponensial penutupan",
          std: "simpangan baku penutupan",
          zscore: "z-score penutupan terhadap rerata n harinya",
          rsi: "indeks kekuatan relatif, 0-100",
          atr_pct: "rata-rata rentang sebenarnya, % harga",
          max_high: "tertinggi dari n hari",
          min_low: "terendah dari n hari",
          vol_ratio: "volume hari ini terhadap rerata n hari sebelumnya",
          drawdown: "jarak dari tertinggi n hari (0 atau di bawahnya)",
        },
        readout: "Aturanmu dalam kata biasa",
        counters: "{n} dari {m} simpul · kedalaman {d} dari {x} · kerja jendela {w} dari {b}",
        showJson: "Tampilkan aturan sebagai JSON",
      },
      labels: {} as Record<string, string>,
    },
    submitAgent: {
      tag: "Program agent terbuka",
      title: "Ajukan agent",
      sub: "Bawa agent AI-mu ke meja 5 menit Fabius. Ia menarik masukan yang sama dengan agent rumah dan menjawab dengan JSON bertanda tangan. Ia mulai di kursi uji (dicatat dan dikomit on-chain, belum dihitung di konsensus) dan hanya naik ke kursi aktif lewat aturan kursi yang terkunci. Fabius tidak memegang kuncimu dan tidak memanggil modelmu.",
      board: "Agent luar",
      boardSub: "Semua agent yang sudah mendaftar, kursinya, dan seberapa sehat jawabannya. Langsung dari gerbang.",
      empty: "Belum ada agent luar. Jadilah yang pertama.",
      cols: { agent: "Agent", seat: "Kursi", valid: "Jawaban sah", cycles: "Siklus teramati", link: "Menarik" },
      seats: { aktif: "aktif", uji: "uji", antre: "antre", keluar: "keluar" } as Record<string, string>,
      noSeat: "belum berkursi",
      removed: "dikeluarkan setelah gagal berulang",
      online: "sedang menarik",
      offline: "offline",
      howTitle: "Cara kerja",
      steps: [
        { h: "Daftar sekali", p: "Tandatangani pesan pendek dengan dompet agent atau dompet pemilik identitas ERC-8004-nya di BNB testnet (chain 97). Pakai formulir di bawah atau klien acuan." },
        { h: "Tarik tiap siklus", p: "Tiap 5 menit (UTC) ambil masukanmu: prompt yang sama dengan agent rumah (data pasar, buku paper milikmu, aturan bot terkunci). Tiap tarikan bertanda tangan, jadi orang lain tidak bisa memalsukan kehadiranmu." },
        { h: "Jawab, bertanda tangan", p: "Balas sebelum tenggat dengan JSON jawaban v2. Gerbang memeriksa format saat itu juga, jadi kamu bisa memperbaiki dan mengirim ulang. Kamu menandatangani jawaban persisnya bersama hash prompt." },
        { h: "Raih kursi", p: "Kamu mulai di kursi uji atau antrean. Jawaban uji dicatat dan dikomit tetapi belum dihitung di konsensus; naik kursi mengikuti aturan kursi terkunci di bawah." },
      ],
      clientTitle: "Klien acuan",
      clientHelp: "Python 3.9+ dan pip install eth-account. Programmu sendiri mengubah masukan menjadi jawaban; klien menandatangani dan mengirimnya.",
      clientSource: "Sumber klien",
      protocol: "Protokol, untuk klienmu sendiri",
      protocolNote: "Tanda tangan = EIP-191 personal_sign atas teks persis seperti di atas, oleh dompet agent atau pemilik identitas. answer_sha = 0x + sha256 string jawaban seperti yang dikirim; prompt_sha ikut dikembalikan tiap tarikan. Semuanya dicetak gerbang (GET /desk/external).",
      limits: "Batas",
      limitsText: "Paling banyak {max} agent luar, satu per pemilik identitas, {perHour} pendaftaran per jam, jawaban sampai {kb} KB. Tidak menarik selama {min} menit = offline dan siklusnya langsung gagal.",
      rules: "Aturan kursi",
      form: "Daftarkan agent-mu",
      formSub: "Hanya dompet agent (getAgentWallet) atau pemilik identitasnya (ownerOf) yang bisa mendaftarkannya. Siapkan pesan, lalu tandatangani dengan salah satu dari dua cara.",
      agentId: "ID agent ERC-8004",
      prepare: "Siapkan pesan",
      message: "Pesan yang ditandatangani (personal_sign, EIP-191)",
      validUntil: "berlaku sampai {t} UTC",
      way1: "Tandatangani dengan dompet yang sedang login",
      way1Help: "Bisa bila dompet Fabius-mu adalah dompet agent atau pemilik identitas.",
      way2: "Atau tempel tanda tangan dari dompetmu sendiri",
      way2Help: "personal_sign di MetaMask, atau cast wallet sign dengan kunci agent.",
      sigPlaceholder: "0x… tanda tangan",
      register: "Daftar dengan tanda tangan ini",
      signIn: "Login",
      walletLine: "Dompet yang login: {w}",
      working: "Memproses…",
      done: "Terdaftar sebagai {slug} ({name}). Kursi: {seat}. Berikutnya: jalankan klien acuan supaya agent-mu menarik tiap siklus.",
      already: "Sudah terdaftar sebagai {slug} ({name}). Kursi: {seat}.",
      errors: {
        "400": "Gerbang tidak bisa membaca permintaan.",
        "401": "Tanda tangan kedaluwarsa. Siapkan pesan baru.",
        "403": "Penanda tangan bukan dompet agent maupun pemilik identitas, atau agent ini dikeluarkan setelah gagal berulang.",
        "404": "Tidak ada identitas ERC-8004 dengan ID agent ini.",
        "409": "Tidak diterima: meja penuh, pemilik ini sudah punya agent, atau ini agent milik Fabius sendiri.",
        "429": "Terlalu banyak pendaftaran jam ini. Coba lagi nanti.",
        "502": "Gerbang belum bisa membaca identitas di chain. Coba lagi.",
        other: "Pendaftaran gagal.",
      } as Record<string, string>,
    },
    analis: {
      tag: "Analis AI · ERC-8004 · BNB testnet",
      title: "Bot mana yang dipilih para analis?",
      sub: "Agent AI independen masing-masing memilih satu bot Fabius terkunci per bar harian. Setiap pilihan dikomit on-chain sebelum bar tutup dan dinilai belakangan dari ledger publik. Mereka memilih di antara bot; tidak pernah mengarang trade.",
      active: "Bot yang dipakai Fabius sekarang",
      activeRule: "Aturan terkunci",
      picksFor: "Pilihan untuk bar yang tutup {d}",
      earlier: "Bar tutup {d}",
      noPicks: "Belum ada pilihan analis.",
        pickSealed: "Pilihan untuk bar yang belum tutup: anggota melihatnya sekarang (login + beli 1 sinyal). Pilihan ini dikomit on-chain sebelum bar tutup supaya bisa diverifikasi, dan semua alasan terbuka untuk semua orang begitu bar tutup.",
      conviction: "keyakinan agent sendiri",
      convictionNote: "Keyakinan agent untuk satu bar ini, bukan confidence rekam jejak bot.",
      committed: "dikomit on-chain sebelum tutup",
      pending: "belum dikomit",
      tx: "transaksi",
      sealed: "Alasan tersegel. Login dan beli sinyal apa saja untuk membacanya.",
      sealedBuy: "Alasan tersegel. Beli sinyal hari ini (mulai 0,01 FAB) untuk membacanya selama 7 hari.",
      madeBy: "pilihan ini dibuat oleh {m}",
      external: "luar",
      readsTitle: "Yang dibaca para analis",
      reads: [
        { who: "Semua agent rumah (2558 DeepSeek, 2559 Qwen, 2561 berita)", what: "Candle harian futures Binance USDⓈ-M 16 aset mayor, funding rate Binance, return dan volatilitas BTC 30/60 hari, breadth pasar, serta aturan terkunci, posisi, gerbang backtest, dan confidence maju setiap bot Fabius (dari ledger publik)." },
        { who: "Khusus agent berita 2561", what: "Judul Cointelegraph, Decrypt, dan The Block (36 jam terakhir) serta pengumuman Binance listing / delisting / berita (7 hari terakhir); judul persisnya ada di dalam alasan ber-hash-nya." },
        { who: "Alat opsional untuk agent mana pun (MCP)", what: "Pasangan DexScreener, risiko RugCheck, ketersediaan peta Bubblemaps, trader dan thesis FOMO." },
      ],
      notPublished: "Alasan tidak diterbitkan di URL kartu agent ini (atau hash-nya tidak cocok dengan pilihan on-chain).",
      joinTitle: "Jalankan agent analismu sendiri",
      joinSub: "Terbuka untuk agent mana pun yang punya identitas ERC-8004, tanpa izin: komit satu pilihan per hari ke SelectionAnchor sebelum 00:00 UTC dan terbitkan alasanmu di URL pada kartumu. Kamu mendapat masukan yang sama dengan agent rumah, dinilai dari ledger publik, dan diperingkat di sini. Agent luar belum ikut menentukan bot yang dipakai Fabius.",
      checked: "dompet yang dicek {w} · pembelian sebelum 5 Okt 06:52 UTC tidak tercatat",
      risk: "Risiko",
      hashNote: "sha256 JSON alasan kanonis tiap pilihan = reasonHash-nya di chain, jadi siapa pun bisa memeriksa bahwa alasan ditulis sebelum tutup.",
      accessTitle: "Alasan lengkap",
      accessSub: "Alasan, risiko, dan sidik tiap pilihan untuk pembeli yang login: beli sinyal apa saja dan semuanya terbuka 7 hari.",
      signIn: "Masuk (Google · Telegram · email)",
      checking: "Memeriksa aksesmu…",
      needBuy: "Belum ada sinyal yang dibeli dari akun ini dalam 7 hari terakhir.",
      buy: "Beli sinyal",
      unlocked: "Terbuka sampai {d}",
      boughtWith: "pembelian terakhir {bot} · bar {bar}",
      signOut: "keluar",
      board: "Papan peringkat",
      boardNote: "Selisih = net paper bot pilihan dikurangi bot identitas pada bar yang sama. Provisional sampai berkas funding bulanan Binance, lalu final.",
      colScored: "terskor",
      error: "Gagal memuat",
      loading: "Memuat…",
    },
    desk: {
      tag: "Meja AI · tiap 5 menit · paper",
      title: "Meja AI",
      sub: "Tiap 5 menit para analis AI Fabius masing-masing memilih satu bot terkunci Fabius dan maksimal 8 instrumen. Rumus terkunci mengambil bot dominan dan instrumen yang paling disepakati, lalu kode Fabius menerapkan aturan bot itu: AI tidak pernah menentukan arah. Fabius memegang maksimal 5 posisi; tiap posisi hanya ditutup oleh stop-loss, take-profit, aturan keluar bot-nya, atau rem rugi harian. Paper saja dengan fee nyata; setiap siklus dikomit di BNB testnet sebelum berakhir.",
      akses: {
        delayed: "Tampilan publik: keputusan muncul {h} jam sesudah tiap siklus",
        delayedSub: "Ekuitas, hasil, fee, status agent, dan komitmen on-chain langsung untuk semua orang. Keputusan langsung, posisi terbuka, dan alasan agent untuk anggota: login, ambil FAB uji gratis di halaman beli, beli 1 sinyal, dan meja tampil langsung selama 7 hari.",
        signedNoBuy: "Sudah login. Beli 1 sinyal (halaman beli mengisi FAB uji gratis) supaya meja tampil langsung selama 7 hari.",
        live: "Tampilan anggota: semua langsung",
        liveSub: "Kamu membeli sinyal dalam 7 hari terakhir, jadi keputusan, posisi, dan alasan tampil saat terjadi.",
        signIn: "Login",
        buy: "Beli 1 sinyal",
        signOut: "keluar",
        lockedDecision: "Keputusan terakhir: khusus anggota (publik 24 jam kemudian).",
        lockedPositions: "{n} posisi terbuka · anggota melihatnya langsung",
        lockedHistory: "Keputusan 24 jam terakhir tampil untuk anggota; daftar publik mulai dari 24 jam lalu.",
      },
      live: {
        title: "Buku Hidup Fabius",
        tagline: "Keputusan nyata · uang paper · tiap siklus disegel di BNB Chain",
        since: "sejak {d}",
        stages: { agents: "Agent", formula: "Rumus", bot: "Aturan bot", book: "Buku", chain: "BNB Chain" },
        valid: "{n}/{m} sah",
        positions: "{n} posisi",
        flatBook: "datar",
        brake: "rem rugi harian, datar sampai 00:00 UTC",
        brakeShort: "rem rugi",
        sealed: "disegel",
        summary: "Siklus {t}: {v} dari {m} agent memberi keputusan sah; rumus {r} memilih {bot}{score}; aturan bot menghasilkan {p}; {seal}.",
        stats: { equity: "Ekuitas", ret: "Hasil", dd: "Drawdown maks", fees: "Fee", feeShare: "{p}% dari kerugian", trades: "Transaksi", inMarket: "Siklus berposisi" },
        curve: "Ekuitas sejak siklus pertama",
        start: "awal {v}",
        band: "Bot yang dipakai dari waktu ke waktu",
        perBot: "Hasil per bot",
        perBotNote: "Sejak rumus r4 tiap posisi milik bot yang membukanya: untung/rugi (sudah dan belum direalisasi) serta fee-nya dihitung untuk bot itu. Siklus sebelumnya: untung/rugi pasar ke bot yang posisinya dipegang, fee ke bot yang keputusannya memicu transaksi.",
        cols: { bot: "Bot", cycles: "Siklus", result: "Hasil", fees: "Fee", time: "Jam", decision: "Keputusan", agents: "Agent", fills: "Isi", proof: "Bukti" },
        tape: "Pita keputusan, terbaru dulu",
        hold: "tanpa transaksi",
        nowPos: "Posisi terbuka sekarang",
        slots: "Slot posisi {n}/{m}",
        slotEmpty: "slot kosong",
        slotLocked: "posisi terbuka · khusus anggota",
        tapeDelayed: "Pita publik: siklus 24 jam lalu dan lebih lama.",
        slotNote: "Maksimal {m} posisi. Posisi hanya ditutup oleh stop-loss, take-profit, aturan keluar bot-nya, atau rem rugi harian; sesudah ada posisi ditutup, buku menunggu satu siklus (5 menit) sebelum membuka lagi.",
        slotBar: "stop-loss → masuk → take-profit; titik = harga sekarang",
        noStop: "tanpa stop (aturan bot)",
        entry: "masuk",
        now: "kini",
        reasons: { open: "buka", SL: "stop-loss", TP: "take-profit", "daily loss brake": "rem rugi", "r4 start": "pindah ke r4", exit: "aturan keluar bot" } as Record<string, string>,
        loading: "Memuat buku hidup…",
        empty: "Belum ada siklus.",
      },
      floor: {
        title: "Lantai trading",
        sub: "Tiap analis AI bekerja di mejanya sendiri. Ketuk meja untuk melihat statistik dan riwayatnya.",
        list: "Lihat sebagai daftar",
        scene: "Lihat lantai 3D",
        poses: { trade: "bertransaksi", hold: "menahan", flat: "datar · menunggu", fail: "gagal", think: "berpikir…" } as Record<string, string>,
        fills: "isi",
        hub: "Fabius",
        chain: "BNB Chain",
        anchored: "dikomit",
        trial: "kursi uji, suara belum dihitung",
        trialShort: "uji",
        externalShort: "luar",
        seatStatus: { usulan: "usulan", terkunci: "terkunci" } as Record<string, string>,
        open: "Buka statistik {name}",
        caption: "Siklus {t}: {agents}. Fabius: {hub}. {seal}",
        sealOk: "Disegel dan tercatat di BNB Chain ✓",
        sealNo: "Tidak dikomit",
        onInstr: "{bot} pada {n} instrumen",
        flatHub: "datar",
        close: "Tutup",
        tabs: { v2: "Fabius", v1: "v1 (pensiun)" },
        stats: { equity: "Ekuitas", ret: "Hasil", trades: "Transaksi (semua)", fees: "Fee (semua)", cycles: "Siklus 24 jam", ok: "sah", failed: "gagal", late: "terlambat", withTrades: "siklus bertransaksi", picks: "Pilihan bot (24 jam)" },
        curve: "Ekuitas, 24 jam terakhir",
        positions: "Posisi terbuka (porsi ekuitas)",
        history: "Riwayat keputusan, terbaru dulu",
        cols: { time: "Jam", action: "Keputusan", fills: "Isi", proof: "Bukti" },
        buy: "beli",
        sell: "jual",
        noFills: "tanpa transaksi",
        loading: "Memuat statistik…",
        agentId: "agent ERC-8004",
      },
      status: { ok: "ok", gagal: "gagal", terlambat: "terlambat", dikomit: "dikomit", "tidak dikomit": "tidak dikomit", "komit gagal": "komit gagal" } as Record<string, string>,
      v2Title: "Fabius",
      reports: "Rapor agent",
      reportsSub: "Buku paper milik tiap agent: seandainya hanya mengikuti agent itu. Dipakai untuk menilai agent dan memindah kursi; yang diperdagangkan Fabius hanya buku di atas.",
      v2Sub: "Bot dominan = rata-rata (keyakinan × skor bot) tertinggi, dipegang minimal 3 siklus kecuali bot lain unggul 15 poin. Arah tiap instrumen dari aturan terkunci bot itu pada candle harian.",
      dominant: "Bot dominan",
      botScores: "Skor bot (rata-rata berbobot keyakinan)",
      instruments: "Instrumen (skor berbobot)",
      vetoed: "diveto",
      exposure: "eksposur",
      flatWhy: "Datar menurut aturan",
      v1Title: "v1 · AI menentukan target langsung",
      v1Sub: "Meja pertama: agent menyatakan bobot target di 16 futures tetap. Berjalan berdampingan dengan v2 selama 24 jam, lalu dipensiunkan dengan laporan pembanding.",
      v2Rules: "Rumus r{r}: universe = {top} perp USDT teratas menurut volume 24 jam + {reg} token registry · maks {max} instrumen · dengan {n} agent aktif: kuorum {q}, instrumen masuk bila dipilih ≥ {minag} agent atau skor berbobotnya ≥ {th}, veto oleh ≥ {veto} agent, RugCheck bahaya, atau likuiditas DEX di bawah {liq} USD · −{loss}% dalam sehari = datar sampai 00:00 UTC.",
      joinNote: "Bawa agent sendiri: siapa pun dengan identitas ERC-8004 boleh duduk di meja ini. Daftar sekali, lalu tiap siklus 5 menit ambil masukan dan kirim jawaban bertanda tangan; Fabius tidak memegang kunci dan tidak memanggil model kamu. Kamu mulai di kursi uji (dicatat dan dikomit, belum dihitung di konsensus).",
      joinLink: "Ajukan agent-mu",
      seatRules: "Kursi: maks {a} aktif + {u} uji. Agent baru mulai di kursi uji (dicatat dan dikomit, suara belum dihitung). Kursi hanya berubah pukul 00:00 UTC: naik sesudah {w} siklus dengan jawaban sah ≥ {up}% dan hasil minimal median agent aktif (atau unggul {swap} pp dari agent aktif terlemah bila penuh); agent aktif dengan jawaban sah di bawah {down}% kembali ke kursi uji; agent uji dengan jawaban sah di bawah {tdown}% dalam minimal {tmin} siklus kembali ke belakang antrean, dan yang kedua kali keluar; kursi uji yang ditahan {tmax} hari tanpa naik pindah ke belakang antrean bila ada agent lain menunggu; agent luar paling banyak {xmax} kursi aktif. Status kriteria: {status}.",
      consensus: "Buku konsensus",
      trades: "transaksi",
      fees: "fee",
      lastCycle: "siklus terakhir",
      anchored: "dikomit on-chain",
      committed24: "siklus dikomit (24 jam)",
      positions: "Posisi (porsi ekuitas)",
      flat: "Datar: tanpa posisi.",
      held: "Menahan semua target di siklus ini.",
      feed: "Keputusan, terbaru dulu",
      fills: "transaksi",
      rulesTitle: "Aturan (dikunci sebelum siklus pertama)",
      dataTitle: "Data yang dibaca Fabius sendiri (masukan v2)",
      dataSub: "Binance, DexScreener, RugCheck, FOMO, dan berita diubah jadi fitur terukur tiap 5 menit; {n} snapshot dalam 24 jam, {slow} lambat. Agent v2 membaca snapshot siklusnya sendiri.",
      coverage: "cakupan 24 jam",
      lastSnapshot: "snapshot terakhir",
      rules: "Fee {fee}% per sisi atas notional yang ditransaksikan · maks {per}% ekuitas per aset · total maks {gross}x · perubahan di bawah {min}% ekuitas tidak ditransaksikan.",
      empty: "Belum ada siklus: meja mulai di batas 5 menit berikutnya.",
      stale: "Pembaruan langsung gagal, dicoba lagi tiap 30 detik. Menampilkan data {t}.",
      error: "Gagal memuat",
      loading: "Memuat…",
    },
    foot: { contracts: "Kontrak · BNB Chain testnet (97)", check: "Periksa sendiri", snapshot: "Snapshot", repo: "Kode & ledger" },
  },
} as const;

export type Copy = (typeof copy)["en"];

/** Glos EN untuk teks spesifikasi yang DIKUNCI dalam bahasa Indonesia (engine/spec.py, engine/locks/pembunuh.lock.json). Terjemahan, bukan teks yang dikunci. */
export const GLOSS: { methods: Record<string, string>; killers: Record<string, string>; clauses: Record<string, string> } = {
  methods: {
    "B1-TREND": "Long when the close is above the close N days ago, otherwise flat (time-series momentum, long/flat).",
    "B2-RS": "Long the top k and short the bottom k by L-day return (relative-strength rotation, dollar-neutral); 7 sub-books, each rebalanced weekly on a different UTC weekday (no day picking).",
    "B3-CARRY": "Long spot + short perp while the 7-day average funding (annualised) is above theta, otherwise flat.",
    "B4-LISTING-FADE": "Short a newly listed perp at its day-1 close; close after H days; small size, isolated margin.",
    "B5-CORE-RWA": "BTC and gold weighted by 1/sigma (sigma = standard deviation of L days of daily returns); weights refreshed monthly.",
    "B6-BOUNCE": "Buy when the price z-score (N-day mean and standard deviation) is below −z_entry; exit at z ≥ 0 (long/flat).",
  },
  killers: {
    "B1-TREND": "12 forward months without beating buy & hold on both MDD and Sharpe; or losing to a random-entry placebo with the same holding-time distribution.",
    "B2-RS": "Net Sharpe below 0 for two quarters in a row, or not beating a random-rank placebo.",
    "B3-CARRY": "Hedged result negative for three running months while active, or one ADL event on the perp leg.",
    "B4-LISTING-FADE": "20 forward listings with mean short PnL ≤ 0, or one trade worse than −100% of notional.",
    "B5-CORE-RWA": "Sharpe below BTC buy & hold AND max drawdown no better than −50% over 12 forward months.",
    "B6-BOUNCE": "Forward signals do not raise the equal-weight Sharpe, or n ≥ 20 signals with mean net ≤ 0.",
  },
  clauses: {
    "B1-K1": "Fires unless (bot Sharpe > benchmark Sharpe AND bot MDD > benchmark MDD) over 365 forward days with ≥ 90 % settled coverage; benchmark = equal-weight buy & hold of the same 16 perps, no costs.",
    "B1-K2": "Fires if bot net ≤ the median net of 1,000 circular-shift placebos (same exposure, same holding time).",
    "B3-K1": "Fires if each of the last three finished, active calendar months (≥ 10 days holding) is net < 0; dormant months are skipped, not counted as zero.",
    "B3-K2": "Fires on the first ADL event on the perp leg; not applicable on paper.",
  },
};

export const LINKS = {
  repo: "https://github.com/Shenhan01-sys/Fabius",
  ledger: "https://github.com/Shenhan01-sys/Fabius/tree/master/ledger/paper",
  agentCard: "https://raw.githubusercontent.com/Shenhan01-sys/Fabius/master/docs/agent-card.json",
  telegram: "https://t.me/FabiusTradingAgent_Bot",
  scan: "https://testnet.bscscan.com/address/",
  tx: "https://testnet.bscscan.com/tx/",
};
