// Teks halaman, EN + ID. Sedikit kata: visual yang bercerita. Batas kejujuran: tidak ada klaim keuntungan (docs/design/landing.md).

export type Lang = "en" | "id";

export const copy = {
  en: {
    nav: { journey: "How it works", proof: "Proof feed", book: "Bots", access: "Access", verify: "Verify", status: "Status", cta: "Open proof feed" },
    hero: {
      l1: "SIGNALS",
      l2: "SEALED",
      l3: "BEFORE THE OUTCOME",
      sub: "Fabius runs locked trading bots and commits every signal on BNB Chain before the market answers. Anyone can check it. No profit claims: paper only, for now.",
      primary: "See the proof feed",
      secondary: "Connect an agent",
      badge: "VERIFY YOURSELF · NO KEY · NO GAS · ",
      legend: { sealed: "rules locked on-chain", verified: "signals verified", empty: "empty: the record started" },
      live: "Live from chain 97",
    },
    journey: {
      tag: "01 — One signal",
      title: "From candle close to proof",
      stations: [
        { t: "00:00 UTC", h: "The bar closes", d: "Daily candle settles. Nothing after this moment can enter the signal." },
        { t: "+ seconds", h: "The bot decides", d: "One locked method, one parameter. Output: enter, exit or resize." },
        { t: "+ minutes", h: "Sealed", d: "Every signal is salted and folded into one Merkle root." },
        { t: "≤ 12 h", h: "Committed on BNB Chain", d: "The root lands in SignalAnchor. The block time is the alibi." },
        { t: "after", h: "Opened & checked", d: "Payloads are revealed. Anyone recomputes them from public bars." },
      ],
      verify: "python -X utf8 tools/verify_signals.py",
    },
    proof: {
      tag: "02 — Proof feed",
      title: "The track record, day by day",
      sub: "Each cell is one bot on one day. Holes stay holes: unmeasured is not zero.",
      states: { future: "not yet", prelock: "before lock", pending: "ticked, commit pending", sealed: "sealed", verified: "verified", gap: "gap", missed: "missed" },
      fd16: "Forward test before anything is sold (F-D16)",
      signals: "signals",
      days: "settled days",
      months: "months",
      settleNote: "Final settles wait for Binance's monthly funding file, so early days show none.",
      started: "Clock started",
    },
    book: {
      tag: "03 — The book",
      title: "Ten slots. One identity bot. Rules first.",
      sub: "A bot earns a slot through gates, then 60 days of shadow. Its spec hash is locked before its first trade.",
      identity: "identity",
      shadow: "shadow",
      locked: "spec hashed · no forward clock",
      locks: "Locked on-chain, in this order",
      lockNames: {
        "THRESHOLDS-v1": "Gate thresholds",
        "SPEC B1-TREND": "B1 spec",
        "SPEC B3-CARRY": "B3 spec",
        "SPEC B2-RS": "B2 spec",
        "SPEC B4-LISTING-FADE": "B4 spec",
        "SPEC B5-CORE-RWA": "B5 spec",
        "SPEC B6-BOUNCE": "B6 spec",
        "FABIUS-FD16-MAJU-v1": "Forward-test rules",
        "FABIUS-BUKU-E690": "Slot book · epoch 690",
        "FABIUS-PEMBUNUH-v1": "Kill rules",
        "FABIUS-ANGGARAN-v1": "Gate error budget",
      } as Record<string, string>,
    },
    doors: {
      tag: "04 — Access",
      title: "Two doors. Same proof.",
      human: {
        k: "For people",
        h: "Proof feed",
        open: "Open · free",
        pts: ["Every commit as it lands", "Opened signals, checked against the chain", "The paper record, holes included"],
        cta: "Watch the proof feed",
        cta2: "Get notified on Telegram",
      },
      agent: {
        k: "For agents",
        h: "MCP + x402",
        open: "MCP server · live · tier 0",
        pts: ["Read the proof feed as tools", "Verify any signal against its root", "Pay per signal with x402 when tier 1 opens"],
        cta: "agent-card.json",
      },
      tier1: {
        k: "Tier 1",
        h: "Real-time signals",
        status: "Locked",
        why: "Opens only for a bot that passes the forward test, after a legal review.",
        rings: ["Forward test", "Legal review", "Go"],
        waitlist: "Join the waitlist",
      },
    },
    label: {
      INTI: "Core",
      SEMENTARA: "Provisional",
      note: {
        INTI: "Holds the book's identity slot (builder's choice). Not proof of being the best: no bot has passed the forward test yet.",
        SEMENTARA: "Runs in public, and can be replaced by any bot that meets the criteria.",
      } as Record<string, string>,
      gate: "gate v1",
      verdict: { LOLOS_SHADOW: "passed", TOLAK: "rejected", TIDAK_TERUKUR: "not measurable" } as Record<string, string>,
    },
    claims: "PAPER ONLY · NO EDGE CLAIMED · FORWARD TEST NOT YET MET · VERIFY, DON'T TRUST · EVERY RULE LOCKED BEFORE THE DATA · ",
    verify: {
      tag: "Verify — no key, no gas",
      t1: "Don't trust.",
      t2: "Check it.",
      sub: "Pick a bot and a day. This page reads the public ledger and BNB Chain at this moment, rebuilds every signal from its on-chain payload, and tells you whether it matches what was sealed before the market answered.",
      bot: "Bot",
      bar: "Bar (UTC day)",
      latest: "latest",
      go: "Verify",
      checking: "Reading BNB Chain…",
      stations: [
        { k: "01", h: "Ledger tick", d: "What the bot decided, written by the GitHub chain" },
        { k: "02", h: "Committed on-chain", d: "Merkle root in SignalAnchor; the block time is the alibi" },
        { k: "03", h: "Opened", d: "Each signal's payload revealed on-chain" },
        { k: "04", h: "Recomputed", d: "Leaf and id rebuilt from the payload, matched to the ledger" },
      ],
      verdicts: {
        SAH: "Verified",
        SEALED_NOT_YET_REVEALED: "Sealed, not yet opened",
        ALARM: "Alarm",
        NO_TICK: "No tick",
        BEFORE_LOCK: "Before the lock",
        BAR_NOT_CLOSED: "Bar not closed",
        AWAITING_COMMIT: "Waiting for the commit",
        NOT_COMMITTED: "Not committed",
      } as Record<string, string>,
      explain: {
        SAH: "Every signal of this day was committed before the outcome and recomputes exactly from what was revealed. Proof of timing, not of profit.",
        SEALED_NOT_YET_REVEALED: "The commit is on-chain; some payloads are still sealed. They must be opened within the reveal window.",
        ALARM: "Something does not match. The problems are listed below, exactly as found.",
        NO_TICK: "The public ledger has no tick for this bot on this day.",
        BEFORE_LOCK: "This day is older than the bot's on-chain spec lock, so it could not be committed. Recorded, not hidden.",
        BAR_NOT_CLOSED: "This day has not closed yet.",
        AWAITING_COMMIT: "The tick exists; the commit is still inside its allowed window.",
        NOT_COMMITTED: "The commit window passed without a commit. That is a visible miss.",
      } as Record<string, string>,
      signals: "signals",
      silent: "No signal today: the bot stayed put. The empty root is committed anyway.",
      emitted: "written",
      committed: "committed",
      afterClose: "h after close",
      root: "root",
      leafOk: "leaf recomputes",
      inLedger: "id in ledger",
      tx: "tx",
      problems: "Problems found",
      self: "Check it yourself",
      selfNote: "Same check, without this website:",
      raw: "Raw result (JSON)",
      share: "Link to this check",
      checkedAt: "checked",
      error: "Could not read the chain or the ledger right now. That is not a verdict; try again.",
      fromCalendar: "Verify a day",
    },
    status: {
      tag: "Status — health, not performance",
      t1: "Is the machine",
      t2: "alive today?",
      sub: "One UTC day of operations, read live from the public ledger, BNB Chain and GitHub. No key. A failed read shows as unreadable, never as fine and never as an alarm.",
      overall: { ok: "All stations normal", wait: "Running: waiting on a station", alarm: "Alarm", unreadable: "Partly unreadable" } as Record<string, string>,
      checked: "read",
      refresh: "Read again",
      reading: "Reading the ledger, BNB Chain and GitHub…",
      error: "This page could not read its sources right now. That is not a verdict; try again.",
      dial: { title: "Today's bar", closed: "closed", ago: "h ago", window: "tick window", commitLag: "commit within", revealWin: "reveal within", now: "now", h: "h" },
      bots: { tag: "01 — Stations, per bot", title: "Where today's bar is", sub: "The same bar walks every station. A lamp lights when its step is done; a waiting lamp says what it waits for." },
      stations: {
        close: { h: "Bar closed", who: "00:00 UTC" },
        tick: { h: "Ledger tick", who: "GitHub chain" },
        commit: { h: "Committed", who: "Railway worker → SignalAnchor" },
        reveal: { h: "Opened", who: "Railway worker" },
        kertas: { h: "Venue-rules paper", who: "GitHub chain · Binance + Aster rules · 10 USDT" },
        exec: { h: "Demo execution", who: "Railway · Binance demo → Gist → GitHub ledger" },
      } as Record<string, { h: string; who: string }>,
      codes: {
        CLOSED: "closed",
        TICK_OK: "signals written: {d}",
        TICK_BEFORE_WINDOW: "window opens {at}",
        TICK_IN_WINDOW: "inside the window, polled every 5 min until 11:58 UTC",
        TICK_GAP: "gap recorded: unmeasured, not zero",
        TICK_MISSED: "no tick 12 h after close",
        NEEDS_TICK: "after the tick",
        NEEDS_COMMIT: "after the commit",
        UNREADABLE: "could not read: not a verdict",
        COMMIT_OK: "root committed · signals: {d}",
        COMMIT_GRACE: "grace until {at}",
        WORKER_SILENT: "worker silent for {d} min",
        REVEAL_OK: "{d} opened",
        REVEAL_SILENT: "silent day: nothing to open",
        REVEAL_PENDING: "{d} opened · grace until {at}",
        REVEAL_STUCK: "stuck at {d}",
        KERTAS_OK: "up to date",
        KERTAS_BEHIND: "behind: 1-minute prices for the commit time arrive a day later",
        KERTAS_NA: "not run for this bot",
        EXEC_PRIVATE: "runs with API keys on Railway; its public ledger starts when the report feed is switched on (F-D94)",
        EXEC_OK: "in the public ledger: {d} orders",
        EXEC_OK_REAL: "in the public ledger: {d} (real money)",
        EXEC_OK_SWITCH_OFF: "in the public ledger: {d} demo orders · real-money switch OFF (config/uang_nyata.json)",
        EXEC_OK_SWITCH_ON: "in the public ledger: {d} demo orders · real-money switch ON, no real-money report for this bar yet",
        EXEC_WAIT: "executor acts after the commit; report due by {at}",
        EXEC_MISSING: "no execution report {d} min after the commit",
        EXEC_VIOLATION: "safety violations recorded: {d}",
        EXEC_NA: "not executed for this bot",
      } as Record<string, string>,
      lamps: { ok: "done", wait: "waiting", alarm: "alarm", unreadable: "unreadable", later: "not yet", private: "not public", na: "not applicable" } as Record<string, string>,
      verifyBar: "Verify this bar",
      plant: { tag: "02 — The plant", title: "Fuel, clock and memory", sub: "What keeps the stations running: gas for the committer, the chain head, and when the landing data was last printed." },
      gas: { h: "Committer gas", alert: "operator alert", refill: "builder refills", unit: "tBNB" },
      chain: { h: "BNB Chain testnet", block: "block", commits: "commits on SignalAnchor" },
      snap: { h: "Landing snapshot", printed: "printed", block: "at block" },
      beat: {
        tag: "03 — Heartbeat",
        title: "The GitHub chain that writes the ledger",
        sub: "paper-ledger.yml dispatches itself: one run loops for hours, then starts the next. Its commits carry GitHub's clock, not ours.",
        success: "success",
        failure: "failed",
        running: "running",
        other: "other",
        open: "Open on GitHub",
      },
    },
    bot: {
      tag: "Bot — one locked machine",
      rule: "The rule, as locked",
      gloss: "In English (the locked text is the Indonesian above)",
      param: "parameter",
      tier: "tier",
      assets: "assets",
      specLocked: "spec locked on-chain",
      specHashed: "spec hashed, not locked on-chain",
      clock: "forward clock since",
      role: { identity: "In the book · identity bot · slot", challenger: "Challenger · shadow", idle: "Spec hashed · not running" },
      idle: "This bot has a hashed spec but no forward clock: no ticks, no signals, no record. Shown so nothing is hidden; offered to no one.",
      about: "About this bot",
      book: {
        tag: "Paper book today",
        title: "What it holds right now",
        sub: "The last tick in the public ledger, read live. Paper: a position intent, not an order.",
        held: "held",
        flat: "flat",
        short: "short",
        entered: "new",
        exited: "exited",
        asof: "bar",
        written: "written",
        gross: "gross weight",
        error: "Could not read the public ledger right now. That does not mean flat.",
        none: "No tick yet.",
        verify: "Verify this day",
      },
      days: {
        tag: "Day by day",
        title: "Every closed day leaves a cube",
        sub: "One cube per day since the clock started. Holes stay holes. Click a day to check it against the chain.",
        afterClose: "h after close",
        noTick: "closed, tick pending",
        next: "next",
      },
      locks: {
        tag: "Locked, in time order",
        title: "The rules that bind it",
        sub: "Each lock is a transaction; its block time proves the rule existed before every day judged after it. Days before the spec lock are marked, not hidden.",
        firstTick: "First forward tick written",
      },
      exec: {
        tag: "Executed in a demo account",
        title: "Paper, venue rules, then real fills",
        sub: "The same decision three times: the paper ledger fills at the bar close, the venue-rules paper fills two minutes after the commit, and a Binance demo account fills for real. Virtual balance: no profit numbers.",
        paper: "paper = close",
        kertas: "venue-rules paper",
        real: "real fill",
        none: "no orders: positions already matched the target",
        filled: "weight filled",
        backfill: "backfilled",
        badgeReal: "REAL",
        badgeDemo: "demo",
        realFills: "real-money fills",
        realNote: "Binance live account, one-asset canary <= 10 USDT",
        latency: "commit → last fill",
        fee: "real fee",
        vsKertas: "real vs venue-rules paper",
        violations: "safety violations",
        notional: "notional",
        target: "PRD target",
        info: "measured, no target yet",
        note: "Right of the close mark = worse for us (paid more on a buy, got less on a sell). Every order is checked against the on-chain commit time before it is written: an order sent before its commit would show here as a violation. Source: ledger/eksekusi, written by the GitHub chain from the executor's public Gist.",
        error: "Could not read the execution ledger right now. That does not mean nothing was executed.",
      },
      fd16: {
        tag: "Forward test",
        title: "Nothing is sold before these fill",
        sub: "Locked thresholds (F-D16), counted from the public ledger. Settled days wait for Binance's monthly funding file.",
        conf: "Confidence · forward record",
        confNone: "Not measured: fewer than 2 settled forward days, so no number at all.",
        confEarly: "Early: computed, but below the F-D16 thresholds, so not meaningful yet.",
        confOk: "Measured against the locked F-D16 thresholds.",
        confBasis: "1 − p of the locked F-D16 block bootstrap (null: mean net daily forward return ≤ 0). How sure the forward record is that this bot earns after costs — not the chance that today's signal is right. Never includes assets, direction or size.",
        day: "day",
      },
      kill: {
        tag: "When it dies",
        title: "The kill rule, fixed before the first signal",
        sub: "Part of the spec hash: changing a word means a new bot with a new ledger.",
        clauses: "How the machine checks it",
        locked: "Clauses locked on-chain before any final settle",
        textOnly: "No machine-checked clauses for this bot yet: the text is judged by a person.",
      },
    },
    beli: {
      tag: "Buy a signal · x402 · BNB testnet",
      title: "Buy {bot}'s latest signal",
      sub: "Pay per signal with x402. Sign in with Google, Telegram or email: a wallet is created for you and you pay no gas. FAB is a test token with no value. You pay for delivery and proof, not a secret: the bots are deterministic and open.",
      offer: "The offer",
      confidence: "confidence",
      notMeasured: "not measured yet",
      gate: "locked backtest gate",
      priceRule: "Price from a table locked before any forward data (F-D100): it rises only when the forward record is measured.",
      loading: "Loading…",
      wallet: "Your wallet",
      login: "Sign in (Google · Telegram · email)",
      creating: "creating your wallet…",
      noGas: "no tBNB needed",
      topup: "Get free FAB",
      logout: "sign out",
      payTitle: "Pay and reveal",
      pay: "Pay {fab} FAB and reveal",
      paying: "Signing and settling…",
      needTopup: "Not enough FAB yet: get free FAB above first.",
      result: "Your signal",
      flat: "Flat: no positions this bar.",
      committed: "committed on-chain",
      paidTx: "payment transaction on BscScan",
      disclaimer: "Paper position intents, not orders and not investment advice. Testnet only.",
      botTitle: "Telegram bot payments (optional)",
      botSub: "Let the Fabius bot pay for you so /buy works directly in Telegram. The Fabius server only asks it to sign the exact FAB price of a signal to the Fabius gate (enforced in our code, not yet by a Privy policy). Revoke any time. Testnet test tokens only.",
      botAllow: "Allow Fabius bot to pay for me",
      tgNeed: "Your Telegram is not linked to this wallet yet, so the bot cannot find it. Link it once:",
      tgLink: "Link my Telegram",
      tgWorking: "Linking…",
      tgDone: "Telegram linked. Go back to the chat and send /buy.",
      tgFail: "Telegram link failed",
      tgOk: "Telegram linked ({u}): /buy in the bot uses this wallet.",
      botRevoke: "revoke",
      botOn: "Allowed: /buy now pays directly in Telegram.",
      botOff: "Revoked: the bot can no longer pay from your wallet.",
      rule: "Rule (locked)",
      changes: "Changes vs previous bar",
      enter: "enter",
      exit: "exit",
      noTp: "No take-profit or stop-loss outside the rule: a position exits only when the rule flips, judged on the daily close (00:00 UTC), not intraday.",
      colAsset: "asset",
      colSide: "side",
      colWeight: "weight",
      colEntry: "entry (rule)",
      colExit: "exit next bar if close ≤",
      trailing: "Exit levels move every day with the window: they behave like a trailing stop on the daily close. Entry = close of the first bar of the current long run.",
    },
    foot: { contracts: "Contracts · BNB Chain testnet (97)", check: "Check it yourself", snapshot: "Snapshot", repo: "Source & ledger" },
  },
  id: {
    nav: { journey: "Cara kerja", proof: "Umpan bukti", book: "Bot", access: "Akses", verify: "Periksa", status: "Status", cta: "Buka umpan bukti" },
    hero: {
      l1: "SINYAL",
      l2: "DISEGEL",
      l3: "SEBELUM HASILNYA ADA",
      sub: "Fabius menjalankan bot trading terkunci dan mengomit setiap sinyal ke BNB Chain sebelum pasar menjawab. Siapa pun bisa memeriksa. Tanpa klaim untung: paper dulu.",
      primary: "Lihat umpan bukti",
      secondary: "Hubungkan agen",
      badge: "PERIKSA SENDIRI · TANPA KUNCI · TANPA GAS · ",
      legend: { sealed: "aturan terkunci di chain", verified: "sinyal terbukti", empty: "kosong: rekam jejak baru mulai" },
      live: "Langsung dari chain 97",
    },
    journey: {
      tag: "01 — Satu sinyal",
      title: "Dari tutup lilin sampai terbukti",
      stations: [
        { t: "00:00 UTC", h: "Bar tutup", d: "Lilin harian selesai. Tidak ada yang sesudah detik ini boleh masuk ke sinyal." },
        { t: "+ detik", h: "Bot memutuskan", d: "Satu metode terkunci, satu parameter. Hasil: masuk, keluar, atau ubah ukuran." },
        { t: "+ menit", h: "Disegel", d: "Tiap sinyal diberi garam lalu dilipat jadi satu akar Merkle." },
        { t: "≤ 12 jam", h: "Dikomit ke BNB Chain", d: "Akarnya masuk SignalAnchor. Jam blok adalah alibinya." },
        { t: "sesudah", h: "Dibuka & diperiksa", d: "Isinya dibuka. Siapa pun menghitung ulang dari bar publik." },
      ],
      verify: "python -X utf8 tools/verify_signals.py",
    },
    proof: {
      tag: "02 — Umpan bukti",
      title: "Rekam jejak, hari demi hari",
      sub: "Satu sel = satu bot pada satu hari. Hari bolong tetap bolong: tak terukur bukan nol.",
      states: { future: "belum", prelock: "sebelum kunci", pending: "tick ada, komit menunggu", sealed: "tersegel", verified: "terbukti", gap: "bolong", missed: "terlewat" },
      fd16: "Uji maju sebelum apa pun dijual (F-D16)",
      signals: "sinyal",
      days: "hari settle",
      months: "bulan",
      settleNote: "Settle final menunggu berkas funding bulanan Binance, jadi hari-hari awal belum punya.",
      started: "Jam mulai",
    },
    book: {
      tag: "03 — Buku slot",
      title: "Sepuluh slot. Satu bot identitas. Aturan dulu.",
      sub: "Bot masuk lewat gerbang, lalu 60 hari bayangan. Hash spesifikasinya dikunci sebelum transaksi pertamanya.",
      identity: "identitas",
      shadow: "bayangan",
      locked: "spesifikasi di-hash · belum ada jam maju",
      locks: "Terkunci di chain, dengan urutan ini",
      lockNames: {
        "THRESHOLDS-v1": "Ambang gerbang",
        "SPEC B1-TREND": "Spesifikasi B1",
        "SPEC B3-CARRY": "Spesifikasi B3",
        "SPEC B2-RS": "Spesifikasi B2",
        "SPEC B4-LISTING-FADE": "Spesifikasi B4",
        "SPEC B5-CORE-RWA": "Spesifikasi B5",
        "SPEC B6-BOUNCE": "Spesifikasi B6",
        "FABIUS-FD16-MAJU-v1": "Aturan uji maju",
        "FABIUS-BUKU-E690": "Buku slot · epoch 690",
        "FABIUS-PEMBUNUH-v1": "Aturan buang bot",
        "FABIUS-ANGGARAN-v1": "Anggaran salah gerbang",
      } as Record<string, string>,
    },
    doors: {
      tag: "04 — Akses",
      title: "Dua pintu. Bukti yang sama.",
      human: {
        k: "Untuk manusia",
        h: "Umpan bukti",
        open: "Terbuka · gratis",
        pts: ["Setiap komit begitu masuk", "Sinyal yang dibuka, dicocokkan dengan chain", "Rekam jejak paper, hari bolong ikut tampil"],
        cta: "Lihat umpan bukti",
        cta2: "Kabari saya di Telegram",
      },
      agent: {
        k: "Untuk agen",
        h: "MCP + x402",
        open: "Server MCP · hidup · tingkat 0",
        pts: ["Baca umpan bukti sebagai tool", "Periksa sinyal mana pun terhadap akarnya", "Bayar per sinyal dengan x402 saat tingkat 1 dibuka"],
        cta: "agent-card.json",
      },
      tier1: {
        k: "Tingkat 1",
        h: "Sinyal waktu-nyata",
        status: "Terkunci",
        why: "Hanya dibuka untuk bot yang lolos uji maju, sesudah telaah hukum.",
        rings: ["Uji maju", "Telaah hukum", "Mulai"],
        waitlist: "Masuk daftar tunggu",
      },
    },
    label: {
      INTI: "Inti",
      SEMENTARA: "Sementara",
      note: {
        INTI: "Menempati slot identitas buku (pilihan builder). Bukan bukti terbaik: belum ada bot yang lolos uji maju.",
        SEMENTARA: "Berjalan terbuka, dan bisa digantikan bot mana pun yang memenuhi kriteria.",
      } as Record<string, string>,
      gate: "gerbang v1",
      verdict: { LOLOS_SHADOW: "lolos", TOLAK: "ditolak", TIDAK_TERUKUR: "tak terukur" } as Record<string, string>,
    },
    claims: "PAPER SAJA · TANPA KLAIM EDGE · UJI MAJU BELUM TERPENUHI · PERIKSA, JANGAN PERCAYA · SEMUA ATURAN DIKUNCI SEBELUM DATA · ",
    verify: {
      tag: "Periksa — tanpa kunci, tanpa gas",
      t1: "Jangan percaya.",
      t2: "Periksa.",
      sub: "Pilih bot dan hari. Halaman ini membaca ledger publik dan BNB Chain saat ini juga, menyusun ulang setiap sinyal dari isinya di chain, lalu memberi tahu apakah cocok dengan yang disegel sebelum pasar menjawab.",
      bot: "Bot",
      bar: "Bar (hari UTC)",
      latest: "terbaru",
      go: "Periksa",
      checking: "Membaca BNB Chain…",
      stations: [
        { k: "01", h: "Tick ledger", d: "Keputusan bot, ditulis rantai GitHub" },
        { k: "02", h: "Dikomit di chain", d: "Akar Merkle di SignalAnchor; jam blok adalah alibinya" },
        { k: "03", h: "Dibuka", d: "Isi tiap sinyal diungkap di chain" },
        { k: "04", h: "Dihitung ulang", d: "Leaf dan id disusun ulang dari isinya, dicocokkan dengan ledger" },
      ],
      verdicts: {
        SAH: "SAH",
        SEALED_NOT_YET_REVEALED: "Tersegel, belum dibuka",
        ALARM: "Alarm",
        NO_TICK: "Tidak ada tick",
        BEFORE_LOCK: "Sebelum kunci",
        BAR_NOT_CLOSED: "Bar belum tutup",
        AWAITING_COMMIT: "Menunggu komit",
        NOT_COMMITTED: "Tidak dikomit",
      } as Record<string, string>,
      explain: {
        SAH: "Setiap sinyal hari ini dikomit sebelum hasilnya ada dan tersusun ulang persis dari yang dibuka. Bukti waktu, bukan bukti untung.",
        SEALED_NOT_YET_REVEALED: "Komit sudah ada di chain; sebagian isi masih tersegel dan wajib dibuka dalam jendela ungkap.",
        ALARM: "Ada yang tidak cocok. Masalahnya ditulis di bawah apa adanya.",
        NO_TICK: "Ledger publik tidak punya tick untuk bot ini di hari ini.",
        BEFORE_LOCK: "Hari ini lebih tua dari kunci spesifikasi bot di chain, jadi tidak bisa dikomit. Dicatat, tidak disembunyikan.",
        BAR_NOT_CLOSED: "Hari ini belum tutup.",
        AWAITING_COMMIT: "Tick sudah ada; komitnya masih di dalam jendela yang diizinkan.",
        NOT_COMMITTED: "Jendela komit lewat tanpa komit. Itu kelalaian yang terlihat.",
      } as Record<string, string>,
      signals: "sinyal",
      silent: "Tidak ada sinyal hari ini: bot diam. Akar kosong tetap dikomit.",
      emitted: "ditulis",
      committed: "dikomit",
      afterClose: "j sesudah tutup",
      root: "akar",
      leafOk: "leaf cocok",
      inLedger: "id di ledger",
      tx: "tx",
      problems: "Masalah yang ditemukan",
      self: "Periksa sendiri",
      selfNote: "Pemeriksaan yang sama, tanpa situs ini:",
      raw: "Hasil mentah (JSON)",
      share: "Tautan ke pemeriksaan ini",
      checkedAt: "diperiksa",
      error: "Chain atau ledger tidak terbaca saat ini. Itu bukan vonis; coba lagi.",
      fromCalendar: "Periksa satu hari",
    },
    status: {
      tag: "Status — kesehatan, bukan kinerja",
      t1: "Mesinnya hidup",
      t2: "hari ini?",
      sub: "Satu hari UTC operasi, dibaca langsung dari ledger publik, BNB Chain, dan GitHub. Tanpa kunci. Gagal baca tampil sebagai tak terbaca, tidak pernah sebagai beres dan tidak pernah sebagai alarm.",
      overall: { ok: "Semua stasiun normal", wait: "Berjalan: menunggu satu stasiun", alarm: "Alarm", unreadable: "Sebagian tak terbaca" } as Record<string, string>,
      checked: "dibaca",
      refresh: "Baca ulang",
      reading: "Membaca ledger, BNB Chain, dan GitHub…",
      error: "Halaman ini tidak bisa membaca sumbernya saat ini. Itu bukan vonis; coba lagi.",
      dial: { title: "Bar hari ini", closed: "tutup", ago: "j lalu", window: "jendela tick", commitLag: "komit dalam", revealWin: "ungkap dalam", now: "sekarang", h: "j" },
      bots: { tag: "01 — Stasiun, per bot", title: "Bar hari ini sedang di mana", sub: "Bar yang sama melewati setiap stasiun. Lampu menyala saat langkahnya selesai; lampu yang menunggu menyebut apa yang ditunggu." },
      stations: {
        close: { h: "Bar tutup", who: "00:00 UTC" },
        tick: { h: "Tick ledger", who: "Rantai GitHub" },
        commit: { h: "Dikomit", who: "Worker Railway → SignalAnchor" },
        reveal: { h: "Dibuka", who: "Worker Railway" },
        kertas: { h: "Kertas aturan venue", who: "Rantai GitHub · aturan Binance + Aster · 10 USDT" },
        exec: { h: "Eksekusi demo", who: "Railway · demo Binance → Gist → ledger GitHub" },
      } as Record<string, { h: string; who: string }>,
      codes: {
        CLOSED: "tutup",
        TICK_OK: "sinyal ditulis: {d}",
        TICK_BEFORE_WINDOW: "jendela buka {at}",
        TICK_IN_WINDOW: "di dalam jendela, dicek tiap 5 menit sampai 11:58 UTC",
        TICK_GAP: "bolong tercatat: tak terukur, bukan nol",
        TICK_MISSED: "tidak ada tick 12 jam sesudah tutup",
        NEEDS_TICK: "sesudah tick",
        NEEDS_COMMIT: "sesudah komit",
        UNREADABLE: "tak terbaca: bukan vonis",
        COMMIT_OK: "akar dikomit · sinyal: {d}",
        COMMIT_GRACE: "tenggang sampai {at}",
        WORKER_SILENT: "worker diam {d} menit",
        REVEAL_OK: "{d} dibuka",
        REVEAL_SILENT: "hari diam: tidak ada yang dibuka",
        REVEAL_PENDING: "{d} dibuka · tenggang sampai {at}",
        REVEAL_STUCK: "tertahan di {d}",
        KERTAS_OK: "mutakhir",
        KERTAS_BEHIND: "tertinggal: harga 1 menit di jam komit baru terbit sehari kemudian",
        KERTAS_NA: "tidak dijalankan untuk bot ini",
        EXEC_PRIVATE: "berjalan dengan kunci API di Railway; ledger publiknya mulai saat umpan laporan dinyalakan (F-D94)",
        EXEC_OK: "di ledger publik: {d} order",
        EXEC_OK_REAL: "di ledger publik: {d} (uang nyata)",
        EXEC_OK_SWITCH_OFF: "di ledger publik: {d} order demo · sakelar uang nyata MATI (config/uang_nyata.json)",
        EXEC_OK_SWITCH_ON: "di ledger publik: {d} order demo · sakelar uang nyata NYALA, belum ada laporan uang nyata bar ini",
        EXEC_WAIT: "eksekutor bertindak sesudah komit; laporan paling lambat {at}",
        EXEC_MISSING: "tidak ada laporan eksekusi {d} menit sesudah komit",
        EXEC_VIOLATION: "pelanggaran keselamatan tercatat: {d}",
        EXEC_NA: "tidak dieksekusi untuk bot ini",
      } as Record<string, string>,
      lamps: { ok: "selesai", wait: "menunggu", alarm: "alarm", unreadable: "tak terbaca", later: "belum", private: "tidak publik", na: "tidak berlaku" } as Record<string, string>,
      verifyBar: "Periksa bar ini",
      plant: { tag: "02 — Mesin", title: "Bahan bakar, jam, dan ingatan", sub: "Yang membuat stasiun tetap jalan: gas untuk committer, kepala chain, dan kapan data landing terakhir dicetak." },
      gas: { h: "Gas committer", alert: "alert operator", refill: "builder isi ulang", unit: "tBNB" },
      chain: { h: "BNB Chain testnet", block: "blok", commits: "komit di SignalAnchor" },
      snap: { h: "Snapshot landing", printed: "dicetak", block: "di blok" },
      beat: {
        tag: "03 — Detak",
        title: "Rantai GitHub yang menulis ledger",
        sub: "paper-ledger.yml memicu dirinya sendiri: satu run berputar berjam-jam, lalu memulai run berikutnya. Komitnya membawa jam GitHub, bukan jam kami.",
        success: "sukses",
        failure: "gagal",
        running: "berjalan",
        other: "lain",
        open: "Buka di GitHub",
      },
    },
    bot: {
      tag: "Bot — satu mesin terkunci",
      rule: "Aturannya, persis seperti dikunci",
      gloss: "",
      param: "parameter",
      tier: "tier",
      assets: "aset",
      specLocked: "spesifikasi dikunci di chain",
      specHashed: "spesifikasi di-hash, belum dikunci di chain",
      clock: "jam maju sejak",
      role: { identity: "Di buku · bot identitas · slot", challenger: "Penantang · bayangan", idle: "Spesifikasi di-hash · tidak berjalan" },
      idle: "Bot ini punya spesifikasi yang di-hash tapi tanpa jam maju: tanpa tick, tanpa sinyal, tanpa rekam jejak. Ditampilkan agar tidak ada yang disembunyikan; tidak ditawarkan ke siapa pun.",
      about: "Tentang bot ini",
      book: {
        tag: "Buku paper hari ini",
        title: "Yang dipegang saat ini",
        sub: "Tick terakhir di ledger publik, dibaca langsung. Paper: niat posisi, bukan order.",
        held: "dipegang",
        flat: "flat",
        short: "short",
        entered: "baru",
        exited: "keluar",
        asof: "bar",
        written: "ditulis",
        gross: "bobot kotor",
        error: "Ledger publik tidak terbaca saat ini. Itu bukan berarti flat.",
        none: "Belum ada tick.",
        verify: "Periksa hari ini",
      },
      days: {
        tag: "Hari demi hari",
        title: "Tiap hari yang tutup meninggalkan satu kubus",
        sub: "Satu kubus per hari sejak jam mulai. Hari bolong tetap bolong. Klik satu hari untuk memeriksanya terhadap chain.",
        afterClose: "j sesudah tutup",
        noTick: "tutup, tick menunggu",
        next: "berikut",
      },
      locks: {
        tag: "Terkunci, urut waktu",
        title: "Aturan yang mengikatnya",
        sub: "Tiap kunci adalah transaksi; jam bloknya membuktikan aturan sudah ada sebelum setiap hari yang dinilai sesudahnya. Hari sebelum kunci spesifikasi ditandai, tidak disembunyikan.",
        firstTick: "Tick maju pertama ditulis",
      },
      exec: {
        tag: "Dieksekusi di akun demo",
        title: "Paper, aturan venue, lalu isi nyata",
        sub: "Keputusan yang sama tiga kali: ledger paper terisi di penutupan bar, kertas aturan venue terisi dua menit sesudah komit, dan akun demo Binance terisi sungguhan. Saldo virtual: tanpa angka untung.",
        paper: "paper = penutupan",
        kertas: "kertas aturan venue",
        real: "isi nyata",
        none: "tidak ada order: posisi sudah sesuai target",
        filled: "bobot terpenuhi",
        backfill: "susulan",
        badgeReal: "REAL",
        badgeDemo: "demo",
        realFills: "isi uang nyata",
        realNote: "akun Binance asli, canary satu aset <= 10 USDT",
        latency: "komit → isi terakhir",
        fee: "fee nyata",
        vsKertas: "nyata vs kertas",
        violations: "pelanggaran keselamatan",
        notional: "notional",
        target: "target PRD",
        info: "diukur, belum ada target",
        note: "Kanan tanda penutupan = lebih buruk bagi kita (beli lebih mahal, jual lebih murah). Setiap order dicocokkan dengan jam komit di chain sebelum ditulis: order yang dikirim sebelum komitnya akan tampil di sini sebagai pelanggaran. Sumber: ledger/eksekusi, ditulis rantai GitHub dari Gist publik eksekutor.",
        error: "Ledger eksekusi tidak terbaca saat ini. Itu bukan berarti tidak ada eksekusi.",
      },
      fd16: {
        tag: "Uji maju",
        title: "Tidak ada yang dijual sebelum ini penuh",
        sub: "Ambang terkunci (F-D16), dihitung dari ledger publik. Hari settle menunggu berkas funding bulanan Binance.",
        conf: "Confidence · rekam jejak maju",
        confNone: "Belum terukur: kurang dari 2 hari settle maju, jadi tidak ada angka sama sekali.",
        confEarly: "Awal: sudah dihitung, tetapi di bawah ambang F-D16, jadi belum bermakna.",
        confOk: "Terukur terhadap ambang F-D16 yang terkunci.",
        confBasis: "1 − p bootstrap blok F-D16 yang terkunci (H0: rerata net harian maju ≤ 0). Seberapa yakin rekam jejak maju bahwa bot ini untung sesudah ongkos — bukan peluang sinyal hari ini benar. Tidak pernah memuat aset, arah, atau ukuran.",
        day: "hari",
      },
      kill: {
        tag: "Kapan ia dimatikan",
        title: "Aturan buang, ditetapkan sebelum sinyal pertama",
        sub: "Bagian dari hash spesifikasi: mengubah satu kata berarti bot baru dengan ledger baru.",
        clauses: "Cara mesin memeriksanya",
        locked: "Syarat dikunci di chain sebelum ada settle final",
        textOnly: "Belum ada syarat yang diperiksa mesin untuk bot ini: teksnya dinilai manusia.",
      },
    },
    beli: {
      tag: "Beli sinyal · x402 · BNB testnet",
      title: "Beli sinyal terbaru {bot}",
      sub: "Bayar per sinyal dengan x402. Masuk dengan Google, Telegram, atau email: dompet dibuatkan dan kamu tidak membayar gas. FAB token uji tanpa nilai. Yang dibayar adalah pengiriman dan bukti, bukan rahasia: bot-botnya deterministik dan terbuka.",
      offer: "Penawaran",
      confidence: "confidence",
      notMeasured: "belum terukur",
      gate: "gerbang backtest terkunci",
      priceRule: "Harga dari tabel yang dikunci sebelum ada data maju (F-D100): naik hanya bila rekam jejak maju terukur.",
      loading: "Memuat…",
      wallet: "Dompetmu",
      login: "Masuk (Google · Telegram · email)",
      creating: "membuat dompetmu…",
      noGas: "tanpa tBNB",
      topup: "Ambil FAB gratis",
      logout: "keluar",
      payTitle: "Bayar dan buka",
      pay: "Bayar {fab} FAB dan buka",
      paying: "Menandatangani dan settle…",
      needTopup: "FAB belum cukup: ambil FAB gratis di atas dulu.",
      result: "Sinyalmu",
      flat: "Datar: tidak ada posisi di bar ini.",
      committed: "dikomit on-chain",
      paidTx: "transaksi pembayaran di BscScan",
      disclaimer: "Niat posisi paper, bukan order dan bukan saran investasi. Testnet saja.",
      botTitle: "Pembayaran oleh bot Telegram (opsional)",
      botSub: "Izinkan bot Fabius membayar untukmu supaya /buy langsung jalan di Telegram. Server Fabius hanya memintanya menandatangani tepat harga FAB satu sinyal ke gerbang Fabius (dijaga kode kami, belum oleh policy Privy). Bisa dicabut kapan saja. Token uji testnet saja.",
      botAllow: "Izinkan bot Fabius membayar untukku",
      tgNeed: "Telegram-mu belum tertaut ke dompet ini, jadi bot tidak bisa menemukannya. Tautkan sekali:",
      tgLink: "Tautkan Telegram-ku",
      tgWorking: "Menautkan…",
      tgDone: "Telegram tertaut. Kembali ke chat dan kirim /buy.",
      tgFail: "Gagal menautkan Telegram",
      tgOk: "Telegram tertaut ({u}): /buy di bot memakai dompet ini.",
      botRevoke: "cabut",
      botOn: "Diizinkan: /buy sekarang langsung bayar di Telegram.",
      botOff: "Dicabut: bot tidak bisa lagi membayar dari dompetmu.",
      rule: "Aturan (terkunci)",
      changes: "Perubahan vs bar sebelumnya",
      enter: "masuk",
      exit: "keluar",
      noTp: "Tidak ada take-profit atau stop-loss di luar aturan: posisi keluar hanya saat aturan berbalik, dinilai pada penutupan harian (00:00 UTC), bukan intraday.",
      colAsset: "aset",
      colSide: "sisi",
      colWeight: "bobot",
      colEntry: "masuk (aturan)",
      colExit: "keluar bar berikut bila tutup ≤",
      trailing: "Level keluar bergeser tiap hari mengikuti jendela: berperilaku seperti trailing stop pada penutupan harian. Masuk = penutupan bar pertama dari run long yang sedang berjalan.",
    },
    foot: { contracts: "Kontrak · BNB Chain testnet (97)", check: "Periksa sendiri", snapshot: "Snapshot", repo: "Kode & ledger" },
  },
} as const;

export type Copy = (typeof copy)["en"];

/** Glos EN untuk teks spesifikasi yang DIKUNCI dalam bahasa Indonesia (engine/spec.py, engine/locks/pembunuh.lock.json). Terjemahan, bukan teks yang dikunci. */
export const GLOSS: { methods: Record<string, string>; killers: Record<string, string>; clauses: Record<string, string> } = {
  methods: {
    "B1-TREND": "Long when the close is above the close N days ago, otherwise flat (time-series momentum, long/flat).",
    "B2-RS": "Long the top k and short the bottom k by L-day return (relative-strength rotation, dollar-neutral); 7 sub-books, each rebalanced weekly on a different UTC weekday (no day picking).",
    "B3-CARRY": "Long spot + short perp while the 7-day average funding (annualised) is above theta, otherwise flat.",
    "B4-LISTING-FADE": "Short a newly listed perp at its day-1 close; close after H days; small size, isolated margin.",
    "B5-CORE-RWA": "BTC and gold weighted by 1/sigma (sigma = standard deviation of L days of daily returns); weights refreshed monthly.",
    "B6-BOUNCE": "Buy when the price z-score (N-day mean and standard deviation) is below −z_entry; exit at z ≥ 0 (long/flat).",
  },
  killers: {
    "B1-TREND": "12 forward months without beating buy & hold on both MDD and Sharpe; or losing to a random-entry placebo with the same holding-time distribution.",
    "B2-RS": "Net Sharpe below 0 for two quarters in a row, or not beating a random-rank placebo.",
    "B3-CARRY": "Hedged result negative for three running months while active, or one ADL event on the perp leg.",
    "B4-LISTING-FADE": "20 forward listings with mean short PnL ≤ 0, or one trade worse than −100% of notional.",
    "B5-CORE-RWA": "Sharpe below BTC buy & hold AND max drawdown no better than −50% over 12 forward months.",
    "B6-BOUNCE": "Forward signals do not raise the equal-weight Sharpe, or n ≥ 20 signals with mean net ≤ 0.",
  },
  clauses: {
    "B1-K1": "Fires unless (bot Sharpe > benchmark Sharpe AND bot MDD > benchmark MDD) over 365 forward days with ≥ 90 % settled coverage; benchmark = equal-weight buy & hold of the same 16 perps, no costs.",
    "B1-K2": "Fires if bot net ≤ the median net of 1,000 circular-shift placebos (same exposure, same holding time).",
    "B3-K1": "Fires if each of the last three finished, active calendar months (≥ 10 days holding) is net < 0; dormant months are skipped, not counted as zero.",
    "B3-K2": "Fires on the first ADL event on the perp leg; not applicable on paper.",
  },
};

export const LINKS = {
  repo: "https://github.com/Shenhan01-sys/Fabius",
  ledger: "https://github.com/Shenhan01-sys/Fabius/tree/master/ledger/paper",
  agentCard: "https://raw.githubusercontent.com/Shenhan01-sys/Fabius/master/docs/agent-card.json",
  telegram: "https://t.me/FabiusTradingAgent_Bot",
  scan: "https://testnet.bscscan.com/address/",
  tx: "https://testnet.bscscan.com/tx/",
};
